### ISSUE TITLE
Android Crash

### ISSUE THREAD

**Issue by snowbreeze** [OneSignal/OneSignal-Cordova-SDK#157]
Can this be due to me calling the function before device onready?

```
java.lang.NullPointerException
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3463)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3481)
	at android.app.ActivityThread.access$1200(ActivityThread.java:145)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1291)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5099)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:803)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:570)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
	at com.onesignal.OneSignal.removeNotificationOpenedHandler(OneSignal.java:1337)
	at com.plugin.gcm.OneSignalPush.onDestroy(OneSignalPush.java:322)
	at org.apache.cordova.PluginManager.onDestroy(PluginManager.java:297)
	at org.apache.cordova.CordovaWebViewImpl.handleDestroy(CordovaWebViewImpl.java:480)
	at org.apache.cordova.CordovaActivity.onDestroy(CordovaActivity.java:315)
	at android.app.Activity.performDestroy(Activity.java:5286)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1111)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3450)

```

**Comment by jkasten2** [comment]
@snowbreeze This is the same crash as the one you linked to. Going to close this one so we don't have split the discussion.

**Comment by snowbreeze** [comment]
Sure
