### ISSUE TITLE
E/OneSignal: Error Getting Google Registration ID  java.io.IOException: AUTHENTICATION_FAILED

### ISSUE THREAD

**Issue by ritaazar** [OneSignal/OneSignal-Cordova-SDK#183]
Hello, I am getting the following error in my logcat although I have added the Google project Number to the project:
```
E/OneSignal: Error Getting Google Registration ID
                      java.io.IOException: AUTHENTICATION_FAILED
                      at com.google.android.gms.gcm.GoogleCloudMessaging.zza(Unknown Source)
                      at com.google.android.gms.gcm.GoogleCloudMessaging.zza(Unknown Source)
                      at com.google.android.gms.gcm.GoogleCloudMessaging.register(Unknown Source)
                      at com.onesignal.PushRegistratorGPS$2.run(PushRegistratorGPS.java:161)
                      at java.lang.Thread.run(Thread.java:818)
```

And in OneSignal Console, when I go to All Users tab, I get the following error:

![image](https://cloud.githubusercontent.com/assets/19166912/26031892/742c37a2-388c-11e7-93d2-b0dd29b07004.png)

**Comment by jkasten2** [comment]
@ritaazar The `AUTHENTICATION_FAILED` is from the device it self or a networking issue and is thrown from the Google Play services library. See the below issue for more details.
https://github.com/OneSignal/OneSignal-Android-SDK/issues/229
