### ISSUE TITLE
[Android@7.0.0] Heads-up the gradle file is broken (again)

### ISSUE THREAD

**Issue by chancezeus** [OneSignal/OneSignal-Cordova-SDK#280]
Hi all,

For a project I needed a more recent version of the android cordova platform then the one available on npm (one that contains a fix for building multiple architectures). For this reason I installed the latest version (7.0.0) from git (probably hits the "npm" shelf soon) and I could not build the project because of an error spawned from the `build-extras-onesignal.gradle`.

Error from clean project:
```
FAILURE: Build failed with an exception.

* Where:
Script '/home/mark/Documents/test-cordova/platforms/android/onesignal-cordova-plugin/hellocordova-build-extras-onesignal.gradle' line: 1

* What went wrong:
A problem occurred evaluating script.
> /home/mark/Documents/test-cordova/platforms/android/app/AndroidManifest.xml (No such file or directory)
```

Hope this helps before 7.0.0 is available for the masses and everybody runs into this issue.

**Comment by junalmeida** [comment]
+1

**Comment by NazliAksoy** [comment]
[https://cordova.apache.org/announcements/2017/12/04/cordova-android-7.0.0.html](https://cordova.apache.org/announcements/2017/12/04/cordova-android-7.0.0.html)

However this a major breaking change for people creating standalone Cordova Android projects. This also means that the locations of files have changed and have been brought in line to the structure used by Android Studio.
This may affect **plugin.xml** files and **config.xml** files that use edit-config, and make it so plugins that use edit-config will not be able to be compatible with both Android 6.x and Android 7.x. To fix this issue, please do the following in your XML files:

```
<!-- An existing config.xml -->
<edit-config file="AndroidManifest.xml" target="/manifest/application" mode="merge">

<!-- needs to change to -->
<edit-config file="app/src/main/AndroidManifest.xml" target="/manifest/application" mode="merge">
```

I tried but not worked :(

**Comment by kzanagodev** [comment]
+1

**Comment by jkasten2** [comment]
@chancezeus @NazliAksoy Thanks for reporting and the details. We just fixed this in our 2.2.5 update.
https://github.com/OneSignal/OneSignal-Cordova-SDK/releases/tag/2.2.5

CC @junalmeida @kzanagodev

**Comment by rodrigoreal** [comment]
Hey guys, i see it has been fixed on 2.2.5 but when i try to install de plugin `ionic cordova plugin add onesignal-cordova-plugin` i'm getting the error:
`Failed to install 'onesignal-cordova-plugin': Error: ENOENT: no such file or directory, open '/Users/rodrigoreal/Projetos/rodrigo/platforms/android/AndroidManifest.xml'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)`

Anyone have any idea why i'm still getting it?
Thanks

**Comment by jkasten2** [comment]
@rodrigoreal Can you run the following to make sure an old version didn't get installed somehow?
`ionic cordova plugin list`

**Comment by rodrigoreal** [comment]
```
$cordova platform version android
Installed platforms:
  android 7.0.0
Available platforms:
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0
```

```
$ionic cordova plugin list
> cordova plugin ls
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-firebase 0.1.25 "Google Firebase Plugin"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-globalization 1.0.9 "Globalization"
cordova-plugin-inappbrowser 2.0.2 "InAppBrowser"
cordova-plugin-intercom 5.0.1 "Intercom"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-sqlite-storage 2.1.5 "Cordova sqlite storage plugin"
onesignal-cordova-plugin 2.2.5 "OneSignal Push Notifications"```

**Comment by buddh4** [comment]
Same happens for me while `ionic cordova platform add android@7.1.0`:

```
Failed to install 'onesignal-cordova-plugin': Error: ENOENT: no such file or directory, open 'xxx\platforms\android\AndroidManifest.xml'
    at Error (native)
    at Object.fs.openSync (fs.js:642:18)
    at Object.fs.readFileSync (fs.js:510:33)
    at Object.parseElementtreeSync (xxx\platforms\android\cordova\node_modules\cordova-common\src\util\xml-helpers.js:180:27)
    at new AndroidManifest (xxx\platforms\android\cordova\lib\AndroidManifest.js:29:20)
    at AndroidProject.getPackageName (xxx\platforms\android\cordova\lib\AndroidProject.js:99:12)
    at Api.addPlugin (xxx\platforms\android\cordova\Api.js:223:57)
    at handleInstall (xxx\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:594:10)
    at xxx\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:357:28
    at _fulfilled (xxx\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:787:54)
(node:9392) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, open 'xxx\platforms\android\AndroidManifest.xml'
```
```
> cordova plugin ls
cordova-plugin-advanced-http 1.5.10 "Advanced HTTP plugin"
cordova-plugin-badge 0.8.3 "Badge"
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-opener2 2.0.19 "File Opener2"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-plugin-x-socialsharing 5.1.8 "SocialSharing"
cordova-sqlite-storage 2.0.4 "Cordova sqlite storage plugin"
es6-promise-plugin 4.1.0 "Promise"
onesignal-cordova-plugin 2.4.0 "OneSignal Push Notifications"
```

```
$ ionic info

cli packages: (xxx\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : android 7.1.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v6.11.3
    npm               : 6.0.1
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : xxx

Misc:

    backend : pro
```

```
cordova platform version android
Installed platforms:
  android 7.1.0
Available platforms:
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0
```

Seems to be similar to https://github.com/litehelpers/Cordova-sqlite-storage/issues/729
