### ISSUE TITLE
NotificationExtenderService exception on latest version.

### ISSUE THREAD

**Issue by fedorcomander** [OneSignal/OneSignal-Cordova-SDK#283]
I am having problems with latest version. NotificationExtenderService gives an exception. Any ideas?

```
E/OneSignal(16026): Error saving notification record! 
E/OneSignal(16026): java.lang.NullPointerException
E/OneSignal(16026): 	at com.onesignal.NotificationGenerationJob.getAndroidIdWithoutCreate(NotificationGenerationJob.java:82)
E/OneSignal(16026): 	at com.onesignal.NotificationBundleProcessor.saveNotification(NotificationBundleProcessor.java:156)
E/OneSignal(16026): 	at com.onesignal.NotificationBundleProcessor.ProcessJobForDisplay(NotificationBundleProcessor.java:104)
E/OneSignal(16026): 	at com.onesignal.NotificationExtenderService.displayNotification(NotificationExtenderService.java:110)
E/OneSignal(16026): 	at com.onesignal.AcousticProtocolNotificationListener.onNotificationProcessing(AcousticProtocolNotificationListener.java:241)
E/OneSignal(16026): 	at com.onesignal.NotificationExtenderService.processJsonObject(NotificationExtenderService.java:170)
E/OneSignal(16026): 	at com.onesignal.NotificationExtenderService.processIntent(NotificationExtenderService.java:155)
E/OneSignal(16026): 	at com.onesignal.NotificationExtenderService.onHandleWork(NotificationExtenderService.java:123)
E/OneSignal(16026): 	at com.onesignal.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:386)
E/OneSignal(16026): 	at com.onesignal.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:377)
E/OneSignal(16026): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
E/OneSignal(16026): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/OneSignal(16026): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/OneSignal(16026): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/OneSignal(16026): 	at java.lang.Thread.run(Thread.java:841)
D/OneSignalExample(16026): Notification displayed with id: 1176215453
```
Notification is NOT being shown!

Code:
```
final String finalMessage = tempMessage;
                                OverrideSettings overrideSettings = new OverrideSettings();
                                //overrideSettings.androidNotificationId = -1;
                                overrideSettings.extender = new NotificationCompat.Extender() {
                                        @Override
                                        public NotificationCompat.Builder extend(
                                                        NotificationCompat.Builder builder) {

                                                builder.setColor(new BigInteger("ff2088c7", 16).intValue());

                                                builder.setDefaults(0);

                                                builder.setGroup("buzz_messages");
                                                builder.setGroupSummary(true);
                                                builder.setContentText(finalMessage);
                                                builder.setTicker(finalMessage);
                                                
                                                builder.setStyle(new NotificationCompat.BigTextStyle().bigText(finalMessage));
                                                
                                                Log.d("OneSignal", "Set contentText: " + finalMessage);

                                                int soundId = context.getResources().getIdentifier("chime", "raw", context.getPackageName());
                                                Log.d("OneSignal", "Sound Id: " + soundId);
                                                if (soundId != 0) {
                                                        Uri uri = Uri
                                                                        .parse(ContentResolver.SCHEME_ANDROID_RESOURCE
                                                                                        + "://"
                                                                                        + context.getPackageName()
                                                                                        + "/" + soundId);
                                                        Log.d("OneSignal", "Sound Uri: " + uri);
                                                        if (uri != null) {
                                                                builder.setSound(uri);
                                                        }
                                                }
                                                builder.setDefaults(Notification.DEFAULT_LIGHTS | Notification.DEFAULT_VIBRATE);

                                                return builder;
                                        }
                                };

                                OSNotificationDisplayedResult displayedResult = displayNotification(overrideSettings);
                                Log.d("OneSignalExample", "Notification displayed with id: "
                                                + displayedResult.androidNotificationId);
```

**Comment by jkasten2** [comment]
@fedorcomander Closing this issue and linking to your other issue https://github.com/OneSignal/OneSignal-Android-SDK/issues/396 to consolidate them

**Comment by sido420** [comment]
@fedorcomander did you manage to get this to work?
Can you comment on https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/416 with your solution plz?

**Comment by fedorcomander** [comment]
using old version (2.3.4 i think) which works for me.
