### ISSUE TITLE
Android Init and Users Not Subscribed

### ISSUE THREAD

**Issue by PaulPaulDevelops** [OneSignal/OneSignal-Cordova-SDK#290]
Hello everyone,

I'm having a similar issue to [here](https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/202) in my ionic 1 project.

I have noticed that OneSignal (for Android specifically) is:
1.) No longer initializing
2.) No longer having users appear on the dashboard as a result

The init and subscription worked previously, but completely stopped. I reverted any changes I made to the project once I noticed this was occurring. I tried testing on different Android devices to see if it was device specific.

I ran the project through Android Studio and saw this output where it was trying to initialize : 
```
W/PluginManager: THREAD WARNING: exec() call to OneSignalPush.init blocked the main thread for 95ms. Plugin should use CordovaInterface.getThreadPool().
```

Then I saw this in Android Studio as well : 
```
W/OneSignal: OneSignalRestClient: null Error thrown from network stack. 
             java.io.InterruptedIOException: thread interrupted
                 at com.android.okhttp.okio.Timeout.throwIfReached(Timeout.java:145)
                 at com.android.okhttp.okio.Okio$1.write(Okio.java:73)
                 at com.android.okhttp.okio.AsyncTimeout$1.write(AsyncTimeout.java:155)
                 at com.android.okhttp.okio.RealBufferedSink.flush(RealBufferedSink.java:221)
                 at com.android.okhttp.internal.http.HttpConnection.flush(HttpConnection.java:141)
                 at com.android.okhttp.internal.http.HttpTransport.finishRequest(HttpTransport.java:52)
                 at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:904)
                 at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:782)
                 at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:463)
                 at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
                 at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:521)
                 at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
                 at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java)
                 at com.onesignal.OneSignalRestClient.startHTTPConnection(OneSignalRestClient.java:146)
                 at com.onesignal.OneSignalRestClient.access$100(OneSignalRestClient.java:38)
                 at com.onesignal.OneSignalRestClient$4.run(OneSignalRestClient.java:94)
                 at java.lang.Thread.run(Thread.java:761)
```

Any input? If you need me to provide any more information, let me know.

**Comment by jkasten2** [comment]
@PaulPaulDevelops The `blocked the main thread for ###ms` warning is shown by Cordova, it is shown to note that the plugin could be causing some startup delay to your app. It won't create any other issue than that.

From the stack trace the device is not subscribing due to a networking error. The HTTP timeout is being hit so there is some kind of issue with the device reaching onesignal.com. Make sure your device has a stable internet connection and nothing on your ending is blocking onesignal.com. Make sure the data and time is correct on the device as this can create HTTPS validation errors.
