### ISSUE TITLE
handleNotificationOpened not fire when app is not runing

### ISSUE THREAD

**Issue by Flaviocrtt** [OneSignal/OneSignal-Cordova-SDK#291]
Hi, my old phone android 4.4.4 works perfectly, call the handleNotificationOpened everytime, but on another devices with android 6,7 doesn't call the handleNotificationOpened when the app is killed, it just calls when the app is opened.
Thanks

**Comment by jkasten2** [comment]
@Flaviocrtt No matter if the app is running or not `handleNotificationOpened` should each time a notification is tapped on.

Are you initializing OneSignal on the first page in your app? Can you make sure you are not getting any javascript runtime error when your app is cold started that could be creating an issue with this? Also check the logcat for any errors.

**Comment by Flaviocrtt** [comment]
@jkasten2 thank you for answer. 
I use phonegap, plugin onesignal-cordova-plugin 2.1.2
i checked the javascript error and there is no errors. 
if something is wrong on my core, it should not work on any device, as i told you, on my phone it works perfecly.
i tried everythig on my code but no sucesss.
here is where i start:
```

function devicereadyforOneSignal() {
  
    window.plugins.OneSignal.startInit("xxxxxxxxxxxxxx", "000")
    window.plugins.OneSignal.handleNotificationOpened(myapplog)
    window.plugins.OneSignal.endInit();

    window.plugins.OneSignal.getIds(function(ids) {
        PushUserId = ids.userId;
        myapplog("got the push id", PushUserId);
    });
    
    /*window.plugins.OneSignal.getTags(function(tags) {
        alert("Tags Received: " + JSON.stringify(tags));
    });*/
}

document.addEventListener("deviceready", function() {
    
    AppIsReady = true;
    AppReady(); //index.js
    Dispositivo = {manufacturer:device.manufacturer, model:device.model, platform:device.platform, version:device.version, uuid:device.uuid, serial:device.serial};

    devicereadyforOneSignal();
}, false);
```

**Comment by Flaviocrtt** [comment]
Some users have told me that problem, i did not believe and they showed me that it was really opening just the home screen, then i tested on bluestacks and i got the same problem, now i need to fix it.
thanks.

**Comment by jkasten2** [comment]
@Flaviocrtt Thanks for the code, this part of your code looks good. Could you also share your `myapplog` function? There could still be an issue with your code if there is a race condition that does not always happen.

Do you get any errors or warnings from the logcat from bluestacks? If you can get the logcat from there do you see the same issue in the Android emulator or a real device running android 6+? Feel free to attach the full logcat and we can take a look.

**Comment by Flaviocrtt** [comment]
that function just feeds a ul to me know what happened on the app, its like console.log() 
```
var myapplog =  function(a, b, c, d, e, f){
    var log='<li><b>'+ new Date()+'</b>';
    var str = function(x){
        if (x!=undefined){
            if(typeof(x)=='object') x = (JSON.stringify(x));
            log += '<p>'+x+'</p> ';
        }
    };
    str(a);
    str(b);
    str(c);
    str(d);
    str(e);
    str(f);
    log+='<hr></li>';
    if(document.getElementById('UltesteErrors') != null){
        document.getElementById('UltesteErrors').innerHTML += (log);
    }
};
```

**Comment by Flaviocrtt** [comment]
here is the logcat, i didn't know about logcat before.
[logcat.txt](https://github.com/OneSignal/OneSignal-Cordova-SDK/files/1634928/logcat.txt)

**Comment by jkasten2** [comment]
@Flaviocrtt Thanks for the log. I don't see any OneSignal errors in the log. You can try adding `console.log` calls in your myapplog function as well as before and after OneSignal start and end init. You can then search for these in your logcat.

I see the log is from BlueStacks, is it an issue an a real device or emulator as well?

**Comment by Flaviocrtt** [comment]
Hello again, i sent 2 notifications, the first when the app was dead, it wrotes 168 lines on the log, then i sent another notification with the app open and it worked, i called myapplog('called handleNotificationOpened', jsonData), line 600 on the log, the catlog only printed the text, but on my app it printed the jsonData with the sent data.
here is the log, thanks.
[logcat3.txt](https://github.com/OneSignal/OneSignal-Cordova-SDK/files/1639001/logcat3.txt)

**Comment by jkasten2** [comment]
@Flaviocrtt Was the line you added to your app `console.log("called handleNotificationOpened");`? I see 2 entries for "called handleNotificationOpened" logged in 2 different ways.

```java
// lines 39-40
01-17 10:24:38.997 D/SystemWebChromeClient( 5172): file:///android_asset/www/js/_init.js: Line 23 : called handleNotificationOpened
01-17 10:24:38.997 I/chromium( 5172): [INFO:CONSOLE(23)] "called handleNotificationOpened", source: file:///android_asset/www/js/_init.js (23)
```

```java
// lines 600-601
01-17 10:30:52.107 D/SystemWebChromeClient( 5172): file:///android_asset/www/js/_init.js: Line 23 : called handleNotificationOpened
01-17 10:30:52.107 I/chromium( 5172): [INFO:CONSOLE(23)] "called handleNotificationOpened", source: file:///android_asset/www/js/_init.js (23)
```

From this log it seems the `handleNotificationOpened` is firing correctly for you for both notifications.

The only issue I see is that the open of the first notification was not track on OneSignal due to a networking error on the device.
```java
1-17 10:24:39.067 W/OneSignal( 5172): HTTP code: -1 sending Notification Opened Failed
01-17 10:24:39.067 W/OneSignal( 5172): java.io.EOFException
01-17 10:24:39.067 W/OneSignal( 5172): 	at com.android.okhttp.internal.Util.readAsciiLine(Util.java:318
)
01-17 10:24:39.067 W/OneSignal( 5172): 	at com.android.okhttp.internal.http.RawHeaders.fromBytes(RawHeaders.java:308)
01-17 10:24:39.067 W/OneSignal( 5172): 	at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:135)
01-17 10:24:39.067 W/OneSignal( 5172): 	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:644)
01-17 10:24:39.067 W/OneSignal( 5172): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:347)
01-17 10:24:39.067 W/OneSignal( 5172): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
01-17 10:24:39.067 W/OneSignal( 5172): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:503)
01-17 10:24:39.067 W/OneSignal( 5172): 	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:136)
01-17 10:24:39.067 W/OneSignal( 5172): 	at com.onesignal.OneSignalRestClient.startHTTPConnection(OneSignalRestClient.java:146)
01-17 10:24:39.067 W/OneSignal( 5172): 	at com.onesignal.OneSignalRestClient.access$100(OneSignalRestClient.java:38)
01-17 10:24:39.067 W/OneSignal( 5172): 	at com.onesignal.OneSignalRestClient$4.run(OneSignalRestClient.java:94)
01-17 10:24:39.067 W/OneSignal( 5172): 	at java.lang.Thread.run(Thread.java:841)
```

**Comment by Nightsd01** [comment]
@Flaviocrtt Closing due to inactivity... I have tested this issue and was not able to reproduce it myself. If you are still encountering this issue please feel free to respond and I will be happy to reopen the issue.

**Comment by Flaviocrtt** [comment]
Ok, thank you, i did have the time to solve that but now i know it's not about OneSignal plugin problem.

**Comment by Flaviocrtt** [comment]
Hello, just to let you know, OneSignal does not finish immediately and i was calling my personal functions not waiting onesignal call the function handleNotificationOpened.
My app is working now, thank you.
