### ISSUE TITLE
Failed to install for iOS platform

### ISSUE THREAD

**Issue by datiecher** [OneSignal/OneSignal-Cordova-SDK#306]
I'm getting an error when trying to add OneSignal to an existing Ionic 3 project, even though the plugin is successfully installed for Android. I've also tried to remove the iOS platform and adding it back again but the error persists.

Version information:
- Ionic CLI: 3.19.1
- Cordova iOS: 4.5.4
- Ruby: 2.2.5
- Pod: 1.4.0
- Node: 8.5
- Xcode: 9.2
- OS: macOS High Sierra 10.13.2

The error I'm getting:
```
nstalling "onesignal-cordova-plugin" for ios

Failed to install 'onesignal-cordova-plugin': Error: pod: Command failed with exit code 31
    at ChildProcess.whenDone (/Users/admin/Development/ionic/easy4tips/mobile/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

I've also updated pod and it's repo before trying to install the plugin.

**Comment by freeriderND** [comment]
I have the same issue with 2.2.5 version.  
2.2.4 works fine.

**Comment by Nightsd01** [comment]
Thanks for reporting this, well investigate shortly to figure out what’s causing this issue.

**Comment by battika** [comment]
Run `pod repo update` first. It helped in my case.

Reference:
https://documentation.onesignal.com/docs/ionic-sdk-setup

**Comment by Nightsd01** [comment]
@datiecher I am closing this issue due to inactivity - I am assuming `pod repo update` resolved your issue. If it did not please feel free to respond and I'd be more than happy to reopen the issue and investigate further. Cocoapods can be a bit finicky.

**Comment by bhumin3i** [comment]
https://github.com/mlynch/azure-activedirectory-library-for-cordova plugin not working 

ERROR LOG:
```
cordova plugin add /Users/rac/Downloads/azure-activedirectory-library-for-cordova-master
Installing "cordova-plugin-ms-adal" for ios
Installing "cordova-plugin-compat" for ios
Failed to install 'cordova-plugin-ms-adal': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/rac/Desktop/git/rti-campus-app-frontend/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)
(node:5082) UnhandledPromiseRejectionWarning: Error: pod: Command failed with exit code 1
```

**Comment by hemangshah** [comment]
@Nightsd01 you've close this issue where we're waiting for your feedback on the issue. 
May be you can reopen the issue.
