### ISSUE TITLE
Error installing plugin in iOS

### ISSUE THREAD

**Issue by tnovau** [OneSignal/OneSignal-Cordova-SDK#321]
Hi, I´m having a problem with my iOS release. When I try to run it, I get:

> Discovered plugin "onesignal-cordova-plugin" in config.xml. Adding it to the project
Fetching plugin "onesignal-cordova-plugin@^2.2.5" via npm
Installing "onesignal-cordova-plugin" for ios
Failed to install 'onesignal-cordova-plugin': Error: pod: Command failed with exit code 31
    at ChildProcess.whenDone (/Users/ionic/builds/project-1/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
Failed to restore plugin "onesignal-cordova-plugin" from config.xml. You might need to try adding it again. Error: Error: pod: Command failed with exit code 31
--save flag or autosave detected

## Build Summary
__macOS version__ | 10.13.2 | 
__Xcode version__ | Xcode 9.2 Build version 9C40b | 
__Node.js version__ | v8.9.4 | 
__npm version__ | 5.6.0 |

Please, can someone help me?

**Comment by battika** [comment]
Run `pod repo update` first. I had the same issue and it helped.

Reference:
https://documentation.onesignal.com/docs/ionic-sdk-setup

**Comment by Nightsd01** [comment]
@tnovau did running `pod repo update` resolve your issue?

**Comment by Nightsd01** [comment]
@tnovau I am assuming it did....closing this issue due to inactivity. Please feel free to respond if this did not resolve your problem and I'll be happy to reopen and investigate.

**Comment by Alacon** [comment]
Confirmed!
`pod repo update` resolved the issue for me

**Comment by hemangshah** [comment]
> Confirmed!
> `pod repo update` resolved the issue for me

@Alacon this is at project level within the vs code or out side the project globally?

**Comment by tenbits** [comment]
How to solve this in phonegap build?

**Comment by tinemlakar** [comment]
> How to solve this in phonegap build?

Did you found the solution for phonegap build maybe?
