### ISSUE TITLE
Custom icons with android@7.0.0

### ISSUE THREAD

**Issue by jakevis** [OneSignal/OneSignal-Cordova-SDK#341]
It seems we cant copy custom resources in with android 7.0.0 and ionic/cordova.

My Env:

```
cli packages: (C:\Users\visse\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : not installed

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.10.0
    npm               : 5.6.0
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : C:\Program Files (x86)\Android\android-sdk

Misc:

    backend : pro
```

When building I get:

```
> cordova build android
cp: copyFileSync: could not write to dest file (code=ENOENT):C:\Users\visse\source\repos\Queercon-ionic-app\Queercon\platforms\android\res\xml\config.xml

Parsing C:\Users\visse\source\repos\Queercon-ionic-app\Queercon\platforms\android\res\xml\config.xml failed
(node:16068) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'C:\Users\visse\source\repos\Queercon-ionic-app\Queercon\platforms\android\res\xml\config.xml'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.parseElementtreeSync (C:\Users\visse\source\repos\Queercon-ionic-app\Queercon\platforms\android\cordova\node_modules\cordova-common\src\util\xml-helpers.js:180:27)
    at new ConfigParser (C:\Users\visse\source\repos\Queercon-ionic-app\Queercon\platforms\android\cordova\node_modules\cordova-common\src\ConfigParser\ConfigParser.js:30:24)
    at updateConfigFilesFrom (C:\Users\visse\source\repos\Queercon-ionic-app\Queercon\platforms\android\cordova\lib\prepare.js:106:18)
    at Api.module.exports.prepare (C:\Users\visse\source\repos\Queercon-ionic-app\Queercon\platforms\android\cordova\lib\prepare.js:42:20)
    at Api.prepare (C:\Users\visse\source\repos\Queercon-ionic-app\Queercon\platforms\android\cordova\Api.js:192:45)
    at C:\Users\visse\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\cordova\prepare.js:106:36
    at _fulfilled (C:\Users\visse\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\visse\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:816:30)
(node:16068) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16068) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

[00:35:37]  lint finished in 2.88 s
```

Everything is good if i remove the platform and re-add it with `ionic cordova platform add android@6.4.0 --save`

**Comment by jakevis** [comment]
Also FWIW I am using config.xml and these commands to copy the resources:

```
        <resource-file src="resources/android/notification/drawable-hdpi-icon.png" target="res/drawable-hdpi/ic_stat_onesignal_default.png" />
        <resource-file src="resources/android/notification/drawable-mdpi-icon.png" target="res/drawable-mdpi/ic_stat_onesignal_default.png" />
        <resource-file src="resources/android/notification/drawable-xhdpi-icon.png" target="res/drawable-xhdpi/ic_stat_onesignal_default.png" />
        <resource-file src="resources/android/notification/drawable-xxhdpi-icon.png" target="res/drawable-xxhdpi/ic_stat_onesignal_default.png" />
        <resource-file src="resources/android/notification/drawable-xxxhdpi-icon.png" target="res/drawable-xxxhdpi/ic_stat_onesignal_default.png" />
```

**Comment by jkasten2** [comment]
@jakevis Thanks for reporting, it seems something has changed with cordova-android@7.0.0 that does not accept resources on this folder any more. We will take a look and reply back with more details.

**Comment by stefano-rainieri** [comment]
Hello, I have the same problem but i [posted it](https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/222#issuecomment-381068517) in the wrong issue.
Waiting for updates 😃

**Comment by Nightsd01** [comment]
Did not mean to close the issue!

**Comment by stefano-rainieri** [comment]
It works for me!! Thank you @Nightsd01 😄 
I didn't use directly the tag `<resource-file />` in the *config.xml*, but i used the hook `<hook src="hooks/copy_android_notification_icons.js" type="after_prepare" />` as suggested by Ionic Native documentation.
I've changed the script with right destination paths and it's all ok 👍 

```js
#!/usr/bin/env node

var fs = require('fs');
var path = require('path');

var rootDest = 'platforms/android/app/src/main/res';
var files = [{
  'resources/android/push/drawable-hdpi-icon.png':
     path.join(rootDest, 'drawable-hdpi/ic_stat_onesignal_default.png')
}, {
  'resources/android/push/drawable-mdpi-icon.png':
    path.join(rootDest, 'drawable-mdpi/ic_stat_onesignal_default.png')
}, {
  'resources/android/push/drawable-xhdpi-icon.png':
    path.join(rootDest, 'drawable-xhdpi/ic_stat_onesignal_default.png')
}, {
  'resources/android/push/drawable-xxhdpi-icon.png':
    path.join(rootDest, 'drawable-xxhdpi/ic_stat_onesignal_default.png')
}, {
  'resources/android/push/drawable-xxxhdpi-icon.png':
    path.join(rootDest, 'drawable-xxxhdpi/ic_stat_onesignal_default.png')
}];

function createFolder(pathAbsolute) {
  if (!fs.existsSync(pathAbsolute)) {
    fs.mkdirSync(pathAbsolute);
  }

  console.log('Folder ready ', pathAbsolute);
}

module.exports = function(context) {
  var root = context.opts.projectRoot;

  createFolder(path.join(root, rootDest, 'drawable-hdpi'));
  createFolder(path.join(root, rootDest, 'drawable-mdpi'));
  createFolder(path.join(root, rootDest, 'drawable-xhdpi'));
  createFolder(path.join(root, rootDest, 'drawable-xxhdpi'));
  createFolder(path.join(root, rootDest, 'drawable-xxxhdpi'));

  files.forEach(function(obj) {
    Object.keys(obj).forEach(function(key) {
      var src = path.join(root, key);
      var dest = path.join(root, obj[key]);

      if (fs.existsSync(src) && fs.existsSync(path.dirname(dest))) {
        fs.createReadStream(src).pipe(fs.createWriteStream(dest));

        console.log('Copied ' + src + ' to ' + dest);
      }
    });
  });
};
```

**Comment by stefano-rainieri** [comment]
Do you think it's better cordova hook or directly resource-file tag?

**Comment by MoxDesigner** [comment]
hello stefano-rainieri can you please direct me where I find the hooks folder to create the file copy_android_notification_icons.js ?? or where I have to create it, I will get you very much...

**Comment by stefano-rainieri** [comment]
@MoxDesigner the _hooks_ folder is under the root of your project. If you don't have the folder yet, create it under the root. Consider to use it for every kind of hook .js you have to write.

**Comment by Mahluleli-Goodson** [comment]
@stefano-rainieri thanks a lot, your method is the best solution, needs to be added to the official doc
