### ISSUE TITLE
Can't Add Plugin to Ionic Project

### ISSUE THREAD

**Issue by simonbrazell** [OneSignal/OneSignal-Cordova-SDK#372]
**Description:**

The OneSignal plugin fails to install in an existing Ionic project as it is unable to find the `AndroidManifest.xml` file when using Cordova platform Android 7.0.0. See error message and environment details below.

**Environment**

```
$ ionic info

cli packages: (.../.nvm/versions/node/v8.9.4/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.9.4
    npm               : 5.6.0 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.3.1 Build version 9E501 

Environment Variables:

    ANDROID_HOME : .../Library/Android/sdk/

Misc:

    backend : pro
```
```
$ ionic cordova plugin ls
> cordova plugin ls
com.googlemaps.ios 2.7.0 "Google Maps SDK for iOS"
cordova-plugin-badge 0.8.7 "Badge"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googlemaps 2.3.1 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.4-dev "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-sqlite-storage 2.0.4 "Cordova sqlite storage plugin"
onesignal-cordova-plugin 2.4.0 "OneSignal Push Notifications"
```

**Steps to Reproduce Issue:**

1. Add the onesignal-cordova-plugin to a project with Cordova Android 7.0.0

**Anything else:**
```
ionic cordova plugin add onesignal-cordova-plugin
> cordova plugin add onesignal-cordova-plugin --save
Installing "onesignal-cordova-plugin" for android

Failed to install 'onesignal-cordova-plugin': Error: ENOENT: no such file or directory, open '.../platforms/android/AndroidManifest.xml'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.parseElementtreeSync (.../platforms/android/cordova/node_modules/cordova-common/src/util/xml-helpers.js:180:27)
    at new AndroidManifest (.../platforms/android/cordova/lib/AndroidManifest.js:29:20)
    at AndroidProject.getPackageName (.../platforms/android/cordova/lib/AndroidProject.js:99:12)
    at Api.addPlugin (.../platforms/android/cordova/Api.js:223:57)
    at handleInstall (.../.nvm/versions/node/v8.9.4/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:594:10)
    at .../.nvm/versions/node/v8.9.4/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:357:28
    at _fulfilled (....nvm/versions/node/v8.9.4/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (.../.nvm/versions/node/v8.9.4/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:816:30)

(node:15714) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, open '.../platforms/android/AndroidManifest.xml'
(node:15714) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by simonbrazell** [comment]
Apologies, it turns out the issue was in fact with `cordova-sqlite-storage ` and not this plugin.
