### ISSUE TITLE
Cannot use together with cordova-plugin-firebase

### ISSUE THREAD

**Issue by dmastag** [OneSignal/OneSignal-Cordova-SDK#405]
**Description:**

Since last week builds will stop working (`cordova build --release`) if  cordova-plugin-firebase is also installed

Here is the error message:
```
Download https://maven.google.com/com/google/firebase/firebase-crash/11.8.0/firebase-crash-11.8.0.pom
Download https://maven.google.com/com/google/firebase/firebase-core/11.8.0/firebase-core-11.8.0.pom
Download https://maven.google.com/com/google/firebase/firebase-config/11.8.0/firebase-config-11.8.0.pom
Download https://maven.google.com/com/google/firebase/firebase-perf/11.8.0/firebase-perf-11.8.0.pom
Download https://maven.google.com/com/google/firebase/firebase-auth/11.8.0/firebase-auth-11.8.0.pom
Download https://maven.google.com/com/google/firebase/firebase-common/11.8.0/firebase-common-11.8.0.pom
Download https://maven.google.com/com/google/firebase/firebase-analytics/11.8.0/firebase-analytics-11.8.0.pom
Download https://maven.google.com/com/google/firebase/firebase-crash-license/11.8.0/firebase-crash-license-11.8.0.pom
Download https://maven.google.com/com/google/firebase/firebase-iid/11.8.0/firebase-iid-11.8.0.pom
Download https://maven.google.com/com/google/firebase/firebase-auth-license/11.8.0/firebase-auth-license-11.8.0.pom
Download https://maven.google.com/com/google/firebase/firebase-config-license/11.8.0/firebase-config-license-11.8.0.pom
Download https://maven.google.com/com/google/firebase/firebase-perf-license/11.8.0/firebase-perf-license-11.8.0.pom
Download https://maven.google.com/com/google/firebase/firebase-iid-license/11.8.0/firebase-iid-license-11.8.0.pom
Download https://maven.google.com/com/google/firebase/firebase-common-license/11.8.0/firebase-common-license-11.8.0.pom
Download https://maven.google.com/com/google/firebase/firebase-analytics-license/11.8.0/firebase-analytics-license-11.8.0.pom
Download https://maven.google.com/com/google/firebase/firebase-analytics-impl/11.8.0/firebase-analytics-impl-11.8.0.pom
Download https://maven.google.com/com/google/firebase/firebase-analytics-impl-license/11.8.0/firebase-analytics-impl-license-11.8.0.pom
:app:preReleaseBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:releaseCompileClasspath'.
> Could not find com.google.firebase:firebase-measurement-connector:11.8.0.
  Searched in the following locations:
      file:/opt/android-sdk-linux/extras/m2repository/com/google/firebase/firebase-measurement-connector/11.8.0/firebase-measurement-connector-11.8.0.pom
      file:/opt/android-sdk-linux/extras/m2repository/com/google/firebase/firebase-measurement-connector/11.8.0/firebase-measurement-connector-11.8.0.aar
      file:/opt/android-sdk-linux/extras/google/m2repository/com/google/firebase/firebase-measurement-connector/11.8.0/firebase-measurement-connector-11.8.0.pom
      file:/opt/android-sdk-linux/extras/google/m2repository/com/google/firebase/firebase-measurement-connector/11.8.0/firebase-measurement-connector-11.8.0.aar
      file:/opt/android-sdk-linux/extras/android/m2repository/com/google/firebase/firebase-measurement-connector/11.8.0/firebase-measurement-connector-11.8.0.pom
      file:/opt/android-sdk-linux/extras/android/m2repository/com/google/firebase/firebase-measurement-connector/11.8.0/firebase-measurement-connector-11.8.0.aar
      https://maven.google.com/com/google/firebase/firebase-measurement-connector/11.8.0/firebase-measurement-connector-11.8.0.pom
      https://maven.google.com/com/google/firebase/firebase-measurement-connector/11.8.0/firebase-measurement-connector-11.8.0.aar
      https://jcenter.bintray.com/com/google/firebase/firebase-measurement-connector/11.8.0/firebase-measurement-connector-11.8.0.pom
      https://jcenter.bintray.com/com/google/firebase/firebase-measurement-connector/11.8.0/firebase-measurement-connector-11.8.0.aar
      https://repo1.maven.org/maven2/com/google/firebase/firebase-measurement-connector/11.8.0/firebase-measurement-connector-11.8.0.pom
      https://repo1.maven.org/maven2/com/google/firebase/firebase-measurement-connector/11.8.0/firebase-measurement-connector-11.8.0.aar
  Required by:
      project :app > com.google.firebase:firebase-messaging:17.0.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 37s
11 actionable tasks: 11 executed
(node:887) UnhandledPromiseRejectionWarning: Error: /builds/project/my-app/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:releaseCompileClasspath'.
> Could not find com.google.firebase:firebase-measurement-connector:11.8.0.
  Searched in the following locations:
      file:/opt/android-sdk-linux/extras/m2repository/com/google/firebase/firebase-measurement-connector/11.8.0/firebase-measurement-connector-11.8.0.pom
      file:/opt/android-sdk-linux/extras/m2repository/com/google/firebase/firebase-measurement-connector/11.8.0/firebase-measurement-connector-11.8.0.aar
      file:/opt/android-sdk-linux/extras/google/m2repository/com/google/firebase/firebase-measurement-connector/11.8.0/firebase-measurement-connector-11.8.0.pom
      file:/opt/android-sdk-linux/extras/google/m2repository/com/google/firebase/firebase-measurement-connector/11.8.0/firebase-measurement-connector-11.8.0.aar
      file:/opt/android-sdk-linux/extras/android/m2repository/com/google/firebase/firebase-measurement-connector/11.8.0/firebase-measurement-connector-11.8.0.pom
      file:/opt/android-sdk-linux/extras/android/m2repository/com/google/firebase/firebase-measurement-connector/11.8.0/firebase-measurement-connector-11.8.0.aar
      https://maven.google.com/com/google/firebase/firebase-measurement-connector/11.8.0/firebase-measurement-connector-11.8.0.pom
      https://maven.google.com/com/google/firebase/firebase-measurement-connector/11.8.0/firebase-measurement-connector-11.8.0.aar
      https://jcenter.bintray.com/com/google/firebase/firebase-measurement-connector/11.8.0/firebase-measurement-connector-11.8.0.pom
      https://jcenter.bintray.com/com/google/firebase/firebase-measurement-connector/11.8.0/firebase-measurement-connector-11.8.0.aar
      https://repo1.maven.org/maven2/com/google/firebase/firebase-measurement-connector/11.8.0/firebase-measurement-connector-11.8.0.pom
      https://repo1.maven.org/maven2/com/google/firebase/firebase-measurement-connector/11.8.0/firebase-measurement-connector-11.8.0.aar
  Required by:
      project :app > com.google.firebase:firebase-messaging:17.0.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 37s
    at ChildProcess.whenDone (/builds/project/my-app/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
(node:887) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:887) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

It works if I remove either cordova-plugin-firebase or onesignal-cordova-plugin

**Environment**

onesignal-cordova-plugin@2.4.1
cordovaplugin-firebase@1.0.5

**Steps to Reproduce Issue:**

  1. Add the onesignal-cordova-plugin to your project
  2. Add the cordova-plugin-firebase to your project
  3. Attempt to build

**Anything else:**

I noticed that its now trying to get com.google.firebase:firebase-messaging:17.0.0 which was previously firebase-messaging-15.0.2.pom

**Comment by samarthagarwal** [comment]
I get the same issue even after I removed the `cordova-plugin-firebase` plugin.

**Comment by drosde** [comment]
same here. `Required by: project :app > com.onesignal:OneSignal:3.9.1 > com.google.firebase:firebase-messaging:17.0.0`

**Comment by jkasten2** [comment]
@dmastag @samarthagarwal This is now fixed, you may need to run the following to clear out any old Gradle caching from your project.
```bash
cordova platform rm android
cordova platform add android
```

**Comment by dmastag** [comment]
Working for me now. Thanks @jkasten2
