### ISSUE TITLE
Application crashes when using onesignal-cordova-plugin with cordova-plugin-googlemaps

### ISSUE THREAD

**Issue by spinninghamster** [OneSignal/OneSignal-Cordova-SDK#414]
**Description:**
I am using the latest `onesignal-cordova-plugin` (NPM) with the latest `cordova-plugin-googlemaps` (NPM) on PhoneGap Build. The build works fine and there are no errors, but when launching the application it crashes right away. There's no way to even get in. I've tested it by removing either the OneSignal or the Google Maps plugin and in both cases the application works, only when they are used together it crashes.

I managed to get it working by using Google Maps 2.2.8 and OneSignal 2.4.0, but obviously using old versions is not a permanent solution.

**Environment**
- Using PhoneGap cli-7.1.0.
- Using PhoneGap Build
- Tested on Android.

**Anything else:**

Here is the build log of the CRASHING build (using latest versions of both plugins):

```
--------------------------------------------------------------------------------
PROJECT PROPERTIES
--------------------------------------------------------------------------------
# This file is automatically generated by Android Tools.
# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
#
# This file must be checked in Version Control Systems.
#
# To customize properties used by the Ant build system edit
# "ant.properties", and override values to adapt the script to your
# project structure.
#
# To enable ProGuard to shrink and obfuscate your code, uncomment this (available properties: sdk.dir, user.home):
#proguard.config=${sdk.dir}/tools/proguard/proguard-android.txt:proguard-project.txt
# Project target.
target=android-26
android.library.reference.1=CordovaLib
cordova.system.library.1=com.google.android.gms:play-services-location:11.+
cordova.system.library.2=com.android.support:support-v4:26.+
cordova.system.library.3=com.android.support:appcompat-v7:26.+
cordova.system.library.4=com.onesignal:OneSignal:3.10.1
cordova.gradle.include.1=onesignal-cordova-plugin/app-build-extras-onesignal.gradle
cordova.system.library.5=com.google.android.gms:play-services-analytics:11.0.1
```

And here is the build log of the WORKING build (OneSignal 2.4.0 and Google Maps 2.2.8):

```
--------------------------------------------------------------------------------
PROJECT PROPERTIES
--------------------------------------------------------------------------------
# This file is automatically generated by Android Tools.
# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
#
# This file must be checked in Version Control Systems.
#
# To customize properties used by the Ant build system edit
# "ant.properties", and override values to adapt the script to your
# project structure.
#
# To enable ProGuard to shrink and obfuscate your code, uncomment this (available properties: sdk.dir, user.home):
#proguard.config=${sdk.dir}/tools/proguard/proguard-android.txt:proguard-project.txt
# Project target.
target=android-26
android.library.reference.1=CordovaLib
cordova.system.library.1=com.google.android.gms:play-services-location:11.+
cordova.system.library.2=com.google.android.gms:play-services-analytics:11.0.1
cordova.system.library.3=com.android.support:support-v4:26.+
cordova.system.library.4=com.android.support:appcompat-v7:26.+
cordova.gradle.include.1=cordova-plugin-googlemaps/app-tbxml-android.gradle
cordova.system.library.5=com.google.android.gms:play-services-maps:11.8.0
cordova.system.library.6=com.google.android.gms:play-services-location:11.8.0
cordova.system.library.7=com.android.support:support-core-utils:24.1.0
cordova.system.library.8=com.onesignal:OneSignal:3.9.0
cordova.gradle.include.2=onesignal-cordova-plugin/app-build-extras-onesignal.gradle
```

**Comment by spinninghamster** [comment]
I contacted the developers of cordova-plugin-googlemaps and they responded here:
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2398#issuecomment-414761000

Here is their answer:

`It seems firebase library failed, but this plugin does not use it.
Thus, onesignal-cordova-plugin developer has to take care of it. Please ask to them.

    
    --------- beginning of crash
08-21 10:37:28.038 27867-27867/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.spinninghamster.app, PID: 27867
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/zzbq;
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source:2)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6391)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5938)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5853)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.zzbq" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.spinninghamster.app-SrXwZ96iIDu3iIvC0RSZpw==/base.apk"],nativeLibraryDirectories=[/data/app/com.spinninghamster.app-SrXwZ96iIDu3iIvC0RSZpw==/lib/arm64, /system/fake-libs64, /data/app/com.spinninghamster.app-SrXwZ96iIDu3iIvC0RSZpw==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source:2) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:6391) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5938) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5853) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) `

**Comment by spinninghamster** [comment]
How do we resolve this? We can't upgrade to the latest version of OneSignal. We're stuck on 2.4.0

**Comment by jkasten2** [comment]
@spinninghamster Can you updated to PhoneGap cli-8.0.0? This is required to get the Firebase dependencies updated to the correct versions as cordova-plugin-googlemaps is updating play-services dependencies to 15.

**Comment by spinninghamster** [comment]
@jkasten2 Tried that but it's causing too many problems right now as many plugins don't support cli-8.0.0 yet

**Comment by spinninghamster** [comment]
@jkasten2 Updated to cli-8.0.0 and it's crashing as well. Here is the build output:

```
--------------------------------------------------------------------------------
PROJECT PROPERTIES
--------------------------------------------------------------------------------
# This file is automatically generated by Android Tools.
# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
#
# This file must be checked in Version Control Systems.
#
# To customize properties used by the Ant build system edit
# "ant.properties", and override values to adapt the script to your
# project structure.
#
# To enable ProGuard to shrink and obfuscate your code, uncomment this (available properties: sdk.dir, user.home):
#proguard.config=${sdk.dir}/tools/proguard/proguard-android.txt:proguard-project.txt
# Project target.
target=android-26
android.library.reference.1=CordovaLib
cordova.system.library.1=com.google.android.gms:play-services-location:11.+
cordova.system.library.2=com.google.android.gms:play-services-analytics:11.0.1
cordova.system.library.3=com.android.support:support-v4:26.+
cordova.system.library.4=com.android.support:appcompat-v7:26.+
cordova.gradle.include.1=cordova-plugin-googlemaps/app-tbxml-android.gradle
cordova.system.library.5=com.google.android.gms:play-services-maps:11.8.0
cordova.system.library.6=com.google.android.gms:play-services-location:11.8.0
cordova.system.library.7=com.android.support:support-core-utils:24.1.0
cordova.system.library.8=com.onesignal:OneSignal:3.10.1
cordova.gradle.include.2=onesignal-cordova-plugin/app-build-extras-onesignal.gradle
--------------------------------------------------------------------------------
COMPILE OUTPUT
--------------------------------------------------------------------------------
:wrapper

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
Subproject Path: CordovaLib
WARNING: The onesignal-gradle-plugin MUST be before com.android.application!
   Please put onesignal-gradle-plugin first OR update to com.android.tools.build:gradle:3.0.0 or newer!
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
	at build_1hhp3detdvwxxk96e7onhzbjz.run(/build.gradle:143)
The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.
Incremental java compilation is an incubating feature.
The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.
Download https://maven.google.com/com/google/android/gms/play-services-maps/11.8.0/play-services-maps-11.8.0.pom
Download https://maven.google.com/com/google/android/gms/play-services-maps-license/11.8.0/play-services-maps-license-11.8.0.pom
Download https://maven.google.com/com/google/android/gms/play-services-maps-license/11.8.0/play-services-maps-license-11.8.0.aar
Download https://maven.google.com/com/google/android/gms/play-services-maps/11.8.0/play-services-maps-11.8.0.aar
:preBuild UP-TO-DATE
:preDebugBuild UP-TO-DATE
:checkDebugManifest
:preReleaseBuild UP-TO-DATE
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugShaders
:CordovaLib:compileDebugShaders
:CordovaLib:generateDebugAssets
:CordovaLib:mergeDebugAssets
:CordovaLib:mergeDebugProguardFiles
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:compileDebugRenderscript
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:processDebugManifest
:CordovaLib:generateDebugBuildConfig
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:incrementalDebugJavaCompilationSafeguard
:CordovaLib:compileDebugJavaWithJavac
:CordovaLib:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForDebug
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug
:CordovaLib:mergeDebugJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForDebug
:CordovaLib:transformNative_libsWithSyncJniLibsForDebug
:CordovaLib:bundleDebug
:CordovaLib:preReleaseBuild UP-TO-DATE
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl
:CordovaLib:compileReleaseNdk UP-TO-DATE
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseShaders
:CordovaLib:compileReleaseShaders
:CordovaLib:generateReleaseAssets
:CordovaLib:mergeReleaseAssets
:CordovaLib:mergeReleaseProguardFiles
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:compileReleaseRenderscript
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:processReleaseManifest
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
:CordovaLib:incrementalReleaseJavaCompilationSafeguard
:CordovaLib:compileReleaseJavaWithJavac
:CordovaLib:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForRelease
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease
:CordovaLib:mergeReleaseJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForRelease
:CordovaLib:transformNative_libsWithSyncJniLibsForRelease
:CordovaLib:bundleRelease
:prepareAndroidArchCoreRuntime110Library
:prepareAndroidArchLifecycleLivedataCore110Library
:prepareAndroidArchLifecycleRuntime110Library
:prepareAndroidArchLifecycleViewmodel110Library
:prepareComAndroidSupportAnimatedVectorDrawable2711Library
:prepareComAndroidSupportAppcompatV72711Library
:prepareComAndroidSupportCustomtabs2711Library
:prepareComAndroidSupportSupportCompat2711Library
:prepareComAndroidSupportSupportCoreUi2711Library
:prepareComAndroidSupportSupportCoreUtils2711Library
:prepareComAndroidSupportSupportFragment2711Library
:prepareComAndroidSupportSupportMediaCompat2711Library
:prepareComAndroidSupportSupportV42711Library
:prepareComAndroidSupportSupportVectorDrawable2711Library
:prepareComGoogleAndroidGmsPlayServicesAnalytics1101Library
:prepareComGoogleAndroidGmsPlayServicesAnalyticsImpl1101Library
:prepareComGoogleAndroidGmsPlayServicesBase1201Library
:prepareComGoogleAndroidGmsPlayServicesBaseLicense1201Library
:prepareComGoogleAndroidGmsPlayServicesBasement1201Library
:prepareComGoogleAndroidGmsPlayServicesBasementLicense1201Library
:prepareComGoogleAndroidGmsPlayServicesLocation1201Library
:prepareComGoogleAndroidGmsPlayServicesLocationLicense1201Library
:prepareComGoogleAndroidGmsPlayServicesMaps1180Library
:prepareComGoogleAndroidGmsPlayServicesMapsLicense1180Library
:prepareComGoogleAndroidGmsPlayServicesTagmanagerV4Impl1101Library
:prepareComGoogleAndroidGmsPlayServicesTasks1201Library
:prepareComGoogleAndroidGmsPlayServicesTasksLicense1201Library
:prepareComGoogleFirebaseFirebaseCommon1201Library
:prepareComGoogleFirebaseFirebaseCommonLicense1201Library
:prepareComGoogleFirebaseFirebaseIid1201Library
:prepareComGoogleFirebaseFirebaseIidLicense1201Library
:prepareComGoogleFirebaseFirebaseMessaging1201Library
:prepareComGoogleFirebaseFirebaseMessagingLicense1201Library
:prepareComOnesignalOneSignal3101Library
:prepareOrgApacheCordovaCordovaLib630DebugLibrary
:prepareTbxmlAndroidLibrary
:prepareDebugDependencies
:compileDebugAidl
:compileDebugRenderscript
:generateDebugBuildConfig
:generateDebugResValues
:generateDebugResources
:mergeDebugResources
:processDebugManifest
:processDebugResources
:generateDebugSources
:incrementalDebugJavaCompilationSafeguard
:compileDebugJavaWithJavac
:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:compileDebugNdk UP-TO-DATE
:compileDebugSources
:mergeDebugShaders
:compileDebugShaders
:generateDebugAssets
:mergeDebugAssets
:transformClassesWithDexForDebug
:mergeDebugJniLibFolders
:transformNative_libsWithMergeJniLibsForDebug
:processDebugJavaRes UP-TO-DATE
:transformResourcesWithMergeJavaResForDebug
:validateSigningDebug
:packageDebug
:assembleDebug
:cdvBuildDebug

BUILD SUCCESSFUL

Total time: 8.069 secs
Built the following apk(s): 
	/build/outputs/apk-debug.apk
```

**Comment by jkasten2** [comment]
@spinninghamster What plugins and what issues do they have? Not sure if I can help but might have a fews points on what could help.
