### ISSUE TITLE
Java source code files

### ISSUE THREAD

**Issue by sido420** [OneSignal/OneSignal-Cordova-SDK#416]
**Description:**

Where do I put .java source files for background notifications as explained in https://documentation.onesignal.com/docs/android-customizations#section-background-data-and-notification-overriding? And, mentioned in https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/215 + https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/156 + https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/30 ?

Is there a special compilation/build etc step?

**Environment**
onesignal-cordova-plugin 2.3.3 "OneSignal Push Notifications"

**Comment by sido420** [comment]
Is there example project/code somewhere for Cordvoa plugin specifically?

**Comment by sido420** [comment]
Here is what I tried but android build fails on me:

- Removed onesignal plugin
- In a separate folder cloned the OneSignal-Cordova-SDK repo 
- Added the extender sample code from https://documentation.onesignal.com/docs/android-customizations#section-background-data-and-notification-overriding to  https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/master/src/android/com/plugin/gcm/OneSignalPush.java
- Treated this new modified local repo as linked (--link) plugin on my Cordova project
- 'cordova android build' which fails

Did I miss something? 

What I need this background notification specifically is to wake up app or bring it to foreground and show some UI as soon as this notification arrives at the device (w/o any user intervention at the notification receiving device)

**Comment by sido420** [comment]
Please note that err is not about the code (I resolved those already). Its about something build related. Please let me know if you really need to see the err message and I'll run the build for you again. I'm assuming that something is wrong in my steps (above).

**Comment by jkasten2** [comment]
@sido420 The error isn't related to your changes. Do you only get this `Multiple dex files define Lcom/google/android/gms/auth/api/signin/internal/zzo;` error after using a local copy of OneSignal?

Can you try building the same project with the latest released version of OneSignal? If you do get the same error please list your output from `cordova plugin ls`. As well as what Cordova version you are using.

If you are only getting this with you local plugin copy I recommend trying with out `--link`. We haven't tested if this param is compatible with OneSignal.

Lastly I recommend not using `cordova-android-support-gradle-release` with OneSignal. This plugin does it's own aligning through gradle so this may conflict

**Comment by sido420** [comment]
Looks like the instructions provided in docs are not clear. Where exactly should I be putting the  code below? In a separate .java file or in https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/master/src/android/com/plugin/gcm/OneSignalPush.java

The app keeps crashing although I tried putting the code inside the class in OneSignalPush.java and in a separate file. 

```
import android.support.v4.app.NotificationCompat;

import com.onesignal.OSNotificationPayload;
import com.onesignal.NotificationExtenderService;

import java.math.BigInteger;

public class NotificationExtenderExample extends NotificationExtenderService {
   @Override
   protected boolean onNotificationProcessing(OSNotificationReceivedResult receivedResult) {
      OverrideSettings overrideSettings = new OverrideSettings();
      overrideSettings.extender = new NotificationCompat.Extender() {
         @Override
         public NotificationCompat.Builder extend(NotificationCompat.Builder builder) {
            // Sets the background notification color to Green on Android 5.0+ devices.
            return builder.setColor(new BigInteger("FF00FF00", 16).intValue());
         }
      };

      OSNotificationDisplayedResult displayedResult = displayNotification(overrideSettings);
			Log.d("OneSignalExample", "Notification displayed with id: " + displayedResult.androidNotificationId);

      return true;
   }
}
```
I added plugin using below:
```
cordova plugin add ~/path/to/onesignal
```

**Comment by jkasten2** [comment]
@sido420 The instructions aren't specific to Cordova, they are generic instructions for any project. We don't have specific instructions currently. However you can add your `NotificationExtenderExample` class to ether, in a separate `.java` or in the existing `OneSignalPush.java`.

Please provide the full stack trace from your logcat of the crash and we can take a look

**Comment by sido420** [comment]
com.example is app id

```
I/ActivityManager(  561): Process com.example (pid 2341) has died
W/ActivityManager(  561): Scheduling restart of crashed service com.example/.NotificationExtenderExample in 61830ms
I/art     ( 2750): Late-enabling -Xcheck:jni
I/ActivityManager(  561): Start proc 2750:com.example/u0a136 for broadcast com.example/com.google.firebase.iid.FirebaseInstanceIdReceiver
V/NotificationService(  561): pkg=de.blinkt.openvpn canInterrupt=false intercept=true
V/NotificationService(  561): pkg=de.blinkt.openvpn canInterrupt=false intercept=true
V/NotificationService(  561): pkg=de.blinkt.openvpn canInterrupt=false intercept=true
V/NotificationService(  561): pkg=de.blinkt.openvpn canInterrupt=false intercept=true
I/FirebaseInitProvider( 2750): FirebaseApp initialization unsuccessful
D/AndroidRuntime( 2750): Shutting down VM
E/AndroidRuntime( 2750): FATAL EXCEPTION: main
E/AndroidRuntime( 2750): Process: com.example, PID: 2750
E/AndroidRuntime( 2750): java.lang.RuntimeException: Unable to instantiate service com.example.NotificationExtenderExample: java.lang.ClassNotFoundException: Didn't find class "com.example.NotificationExtenderExample" on path: DexPathList[[zip file "/data/app/com.example-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example-2/lib/arm, /vendor/lib, /system/lib]]
E/AndroidRuntime( 2750): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2746)
E/AndroidRuntime( 2750): 	at android.app.ActivityThread.access$1800(ActivityThread.java:151)
E/AndroidRuntime( 2750): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1386)
E/AndroidRuntime( 2750): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 2750): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 2750): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime( 2750): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 2750): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 2750): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime( 2750): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/AndroidRuntime( 2750): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.NotificationExtenderExample" on path: DexPathList[[zip file "/data/app/com.example-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example-2/lib/arm, /vendor/lib, /system/lib]]
E/AndroidRuntime( 2750): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime( 2750): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/AndroidRuntime( 2750): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E/AndroidRuntime( 2750): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2743)
E/AndroidRuntime( 2750): 	... 9 more
E/AndroidRuntime( 2750): 	Suppressed: java.lang.ClassNotFoundException: com.example.NotificationExtenderExample
E/AndroidRuntime( 2750): 		at java.lang.Class.classForName(Native Method)
E/AndroidRuntime( 2750): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E/AndroidRuntime( 2750): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
E/AndroidRuntime( 2750): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E/AndroidRuntime( 2750): 		... 11 more
E/AndroidRuntime( 2750): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
W/ActivityManager(  561): Process com.example has crashed too many times: killing!
```

This happens when I put the class in a separate file NotificationExtenderExample.java in the same folder as OneSignal.java and sent a notification to the device with this app installed. The app crashes.

```
--------- beginning of crash
E/AndroidRuntime(21346): FATAL EXCEPTION: main
E/AndroidRuntime(21346): Process: com.example, PID: 21346
E/AndroidRuntime(21346): java.lang.RuntimeException: Unable to instantiate service com.example.NotificationExtenderExample: java.lang.ClassNotFoundException: Didn't find class "com.example.NotificationExtenderExample" on path: DexPathList[[zip file "/data/app/com.example-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example-1/lib/arm, /vendor/lib, /system/lib]]
E/AndroidRuntime(21346): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2746)
E/AndroidRuntime(21346): 	at android.app.ActivityThread.access$1800(ActivityThread.java:151)
E/AndroidRuntime(21346): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1386)
E/AndroidRuntime(21346): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(21346): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(21346): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime(21346): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21346): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(21346): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime(21346): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/AndroidRuntime(21346): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.NotificationExtenderExample" on path: DexPathList[[zip file "/data/app/com.example-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example-1/lib/arm, /vendor/lib, /system/lib]]
E/AndroidRuntime(21346): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime(21346): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/AndroidRuntime(21346): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E/AndroidRuntime(21346): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2743)
E/AndroidRuntime(21346): 	... 9 more
E/AndroidRuntime(21346): 	Suppressed: java.lang.ClassNotFoundException: com.example.NotificationExtenderExample
E/AndroidRuntime(21346): 		at java.lang.Class.classForName(Native Method)
E/AndroidRuntime(21346): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E/AndroidRuntime(21346): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
E/AndroidRuntime(21346): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E/AndroidRuntime(21346): 		... 11 more
E/AndroidRuntime(21346): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
E/AndroidRuntime(11775): FATAL EXCEPTION: main
```
Above happens when I put the code inside the class in OneSignal.java file.

Also, I did not add the locally modified plugin code using --link.

```
cordova plugin add /path/to/repo/on/local/disk
```

A sample plugin with this code would be really helpful.

**Comment by sido420** [comment]
@jkasten2 were you able to reproduce or have any updates on this issue?

**Comment by jkasten2** [comment]
@sido420 I forgot the detail that if you add a new .java file to the plugin you must declare it in the `plugin.xml`. See this line for the format
https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/master/plugin.xml#L59

**Comment by jkasten2** [comment]
@sido420 Let us know if the above does not help and I can reopen this issue.

**Comment by alexandrmiee** [comment]
The documentation is missing a description of package import. Where does OverrideSettings come from?
```java
import com.onesignal.OSNotificationPayload;
import com.onesignal.NotificationExtenderService;
import com.onesignal.OSNotificationReceivedResult;
import com.onesignal.OSNotificationDisplayedResult;
import com.onesignal.OverrideSettings;
import java.math.BigInteger;
import android.support.v4.app.NotificationCompat;

public class OnesignalBgPush extends NotificationExtenderService {
   @Override
   protected boolean onNotificationProcessing(OSNotificationReceivedResult receivedResult) {
      OverrideSettings overrideSettings = new OverrideSettings();
      overrideSettings.extender = new NotificationCompat.Extender() {
         @Override
         public NotificationCompat.Builder extend(NotificationCompat.Builder builder) {
            // Sets the background notification color to Green on Android 5.0+ devices.
            return builder.setColor(new BigInteger("FF00FF00", 16).intValue());
         }
      };

      OSNotificationDisplayedResult displayedResult = displayNotification(overrideSettings);
      
      return true;
   }
}```

> error: cannot find symbol
import com.onesignal.OverrideSettings;
                    ^
  symbol:   class OverrideSettings
  location: package com.onesignal
