### ISSUE TITLE
Cannot build on iOS -- updating Cocoapods doesn't fix it

### ISSUE THREAD

**Issue by whiterook6** [OneSignal/OneSignal-Cordova-SDK#432]
**Description:**
(Seems related to https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/430). I cannot build our app for iOS at the moment. Something seems to have changed in the past few days.

I have updated cocoapods:

```
% sudo gem install cocoapods
Successfully installed cocoapods-1.5.3
Parsing documentation for cocoapods-1.5.3
Done installing documentation for cocoapods after 3 seconds
1 gem installed
```

**Environment**
I'm using xcode 9.4, cordova 7.1.0, cordova-ios 4.5.1, and the following plugins:

```
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-contacts 2.3.1 "Contacts"
cordova-plugin-crop 0.1.0 "CropPlugin"
cordova-plugin-crosswalk-webview 2.4.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.5 "Device"
cordova-plugin-facebook4 1.7.4 "Facebook Connect"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-google-analytics 1.8.6 "Google Universal Analytics Plugin"
cordova-plugin-googleplus 5.1.1 "Google SignIn"
cordova-plugin-inappbrowser 1.3.0 "InAppBrowser"
cordova-plugin-ios-microphone-permissions 1.0.0 "iOS Permissions"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
onesignal-cordova-plugin 2.4.3 "OneSignal Push Notifications"
phonegap-plugin-barcodescanner 7.1.2 "BarcodeScanner"
```

**Anything else:**
```
Failed to install 'onesignal-cordova-plugin': Error: pod: Command failed with exit code 31
  at ChildProcess.whenDone (./platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
  at emitTwo (events.js:106:13)
  at ChildProcess.emit (events.js:191:7)
  at maybeClose (internal/child_process.js:885:16)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
Error: pod: Command failed with exit code 31
```

Interestingly, my config.xml specifies OneSignalCordova version 2.4.4, but only 2.4.3 is being installed.

**Comment by jkasten2** [comment]
@whiterook6 The error is from Cocoapods. I recommend trying to run the following and add OneSignal again.
```
pod repo update
```

Next I would try running the following to makes sure you have the latest cocoapods.
```
brew upgrade cocoapods
```

Most of the time this these will fix the issue but you can try reinstalling cocoapods if nothing else is working.
```
brew reinstall cocoapods
brew link --overwrite cocoapods
```

**Comment by whiterook6** [comment]
Thanks -- it worked!
