### ISSUE TITLE
Installing plugin fails due to inability to find google play services dependency

### ISSUE THREAD

**Issue by JakeSteam** [OneSignal/OneSignal-Cordova-SDK#445]
**Description:**

When trying to perform a build, or more specifically `cordova plugin add onesignal-cordova-plugin@1.13.1`, the build fails.

This worked on Friday, and can be replicated on multiple devices in the company. I expect the issue may be due to the older google play services repository no longer being hosted, perhaps a later version of this repository uses a newer, still hosted version?

**Environment**

Windows 10 x64 (using git bash for commands), npm, Cordova 6.4.0, Cordova Android 7.1.1.

**Steps to Reproduce Issue:**

1. Try to install the plugin using `cordova plugin add onesignal-cordova-plugin@1.13.1`,  `2.2.0`, `2.4.4` or presumably any other version.

**Anything else:**
All plugins:
```
cordova-plugin-device@1.1.2
cordova-plugin-dialogs@1.2.1
https://github.com/ingenie/google-analytics-plugin.git
cordova-plugin-inappbrowser@1.4.0
cordova-plugin-network-information@1.2.1
cordova-plugin-statusbar@2.1.3
cordova-plugin-whitelist@1.2.2
cordova-plugin-firebase@0.1.12
onesignal-cordova-plugin@1.13.1
https://github.com/nchutchind/App-Launcher-Cordova-Plugin.git
```

Full stacktrace:
```
You have been opted out of telemetry. To change this, run: cordova telemetry on.
Fetching plugin "onesignal-cordova-plugin@1.13.1" via npm
Installing "onesignal-cordova-plugin" for android
ANDROID_HOME=C:\Users\Jake\AppData\Local\Android\Sdk
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_191
Subproject Path: CordovaLib
Incremental java compilation is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugApkCopy'.
   > Could not find com.google.android.gms:play-services-base:12.0.0.
     Required by:
         :android:unspecified > com.google.android.gms:play-services-analytics:11.0.4
         :android:unspecified > com.google.android.gms:play-services-analytics:11.0.4 > com.google.android.gms:play-services-analytics-impl:11.0.4
         :android:unspecified > com.google.android.gms:play-services-analytics:11.0.4 > com.google.android.gms:play-services-tagmanager-v4-impl:11.0.4
   > Could not find com.google.android.gms:play-services-basement:12.0.0.
     Required by:
         :android:unspecified > com.google.android.gms:play-services-analytics:11.0.4
         :android:unspecified > com.google.firebase:firebase-messaging:11.0.4
         :android:unspecified > com.google.firebase:firebase-crash:11.0.4
         :android:unspecified > com.google.android.gms:play-services-analytics:11.0.4 > com.google.android.gms:play-services-analytics-impl:11.0.4
         :android:unspecified > com.google.android.gms:play-services-analytics:11.0.4 > com.google.android.gms:play-services-tagmanager-v4-impl:11.0.4
         :android:unspecified > com.google.firebase:firebase-core:11.0.4 > com.google.firebase:firebase-analytics:11.0.4
         :android:unspecified > com.google.firebase:firebase-core:11.0.4 > com.google.firebase:firebase-analytics:11.0.4 > com.google.firebase:firebase-analytics-impl:11.0.4
   > Could not find com.google.firebase:firebase-iid:12.0.0.
     Required by:
         :android:unspecified > com.google.firebase:firebase-messaging:11.0.4
         :android:unspecified > com.google.firebase:firebase-crash:11.0.4
         :android:unspecified > com.google.firebase:firebase-core:11.0.4 > com.google.firebase:firebase-analytics:11.0.4 > com.google.firebase:firebase-analytics-impl:11.0.4
   > Could not find com.google.firebase:firebase-common:12.0.0.
     Required by:
         :android:unspecified > com.google.firebase:firebase-messaging:11.0.4
         :android:unspecified > com.google.firebase:firebase-crash:11.0.4
         :android:unspecified > com.google.firebase:firebase-core:11.0.4 > com.google.firebase:firebase-analytics:11.0.4
         :android:unspecified > com.google.firebase:firebase-core:11.0.4 > com.google.firebase:firebase-analytics:11.0.4 > com.google.firebase:firebase-analytics-impl:11.0.4
   > Could not find com.google.android.gms:play-services-base:12.0.0.
     Required by:
         :android:unspecified > com.google.firebase:firebase-config:12.0.0
   > Could not find com.google.android.gms:play-services-basement:12.0.0.
     Required by:
         :android:unspecified > com.google.firebase:firebase-config:12.0.0
   > Could not find com.google.firebase:firebase-iid:12.0.0.
     Required by:
         :android:unspecified > com.google.firebase:firebase-config:12.0.0
   > Could not find com.google.firebase:firebase-common:12.0.0.
     Required by:
         :android:unspecified > com.google.firebase:firebase-config:12.0.0
   > Could not find com.google.android.gms:play-services-tasks:12.0.0.
     Required by:
         :android:unspecified > com.google.firebase:firebase-config:12.0.0
   > Could not find com.google.firebase:firebase-config-license:12.0.0.
     Required by:
         :android:unspecified > com.google.firebase:firebase-config:12.0.0
   > Could not find com.google.android.gms:play-services-tasks:12.0.0.
     Required by:
         :android:unspecified > com.google.firebase:firebase-core:11.0.4 > com.google.firebase:firebase-analytics:11.0.4 > com.google.firebase:firebase-analytics-impl:11.0.4

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 7.823 secs
Failed to install 'onesignal-cordova-plugin':Error: cmd: Command failed with exit code 1
    at ChildProcess.whenDone (C:\Repositories\android-feedback\platforms\android\cordova\node_modules\cordova-common\src\superspawn.js:169:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
cmd: Command failed with exit code 1

```

**Comment by jkasten2** [comment]
@JakeSteam We no longer support the 1.X version of the OneSignal SDK. Can you update to the latest 2.4.4 version? I recommend following this setup guide to make sure you have upgraded to the new init functions.
https://documentation.onesignal.com/docs/cordova-sdk-setup

The new API can be found below.
https://documentation.onesignal.com/docs/cordova-sdk

Make sure you have you are using Cordova `android@7.0.0` or newer. This is required to ensure other plugins don't conflict with OneSignal's dependencies. You can run the following to check the version of the android platform you are using.
```
cordova platform add android
```

To update you can run the following if this isn't new enough
```
cordova platform rm android
cordova platform add android
```

Thanks

**Comment by JakeSteam** [comment]
Hi, in the "steps to reproduce" I mentioned I've already tried 2.4.4 among others. It gave an identical error. Considering the exact same code worked on multiple machines a few days ago, surely this is a case with one of your dependencies no longer exists?

Have you actually tried installing the plugin in the last day or two, since it's definitely a recent thing?

**Comment by JakeSteam** [comment]
Actually, looks like updating Cordova to 7.1.1 was the solution. Once that was done, version `1.13.1` worked again. I guess the Google Play Services repos are defined in Cordova.. somehow? I've no idea. 

Thanks anyway.
