### ISSUE TITLE
Android Oreo Categories don't get created

### ISSUE THREAD

**Issue by sambauwens** [OneSignal/OneSignal-Cordova-SDK#486]
**Description:**

I created categories on the OneSignal dashboard, but they don't get created, not while initializing and not when receiving a notification.

I've been scratching my head for more than a day on this problem, but this morning after I increased OneSignal's verbosity, I got the following error :

```
W/System.err: java.lang.NumberFormatException: Invalid BigInteger: #017C96
at java.math.BigInt.invalidBigInteger(BigInt.java:86)
        at java.math.BigInt.checkString(BigInt.java:140)
        at java.math.BigInt.putHexString(BigInt.java:99)
        at java.math.BigInteger.<init>(BigInteger.java:244)
        at com.onesignal.NotificationChannelManager.createChannel(NotificationChannelManager.java:131)
        at com.onesignal.NotificationChannelManager.processChannelList(NotificationChannelManager.java:203)
        at com.onesignal.OneSignal$4.onSuccess(OneSignal.java:873)
        at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:208)
        at java.lang.Thread.run(Thread.java:764)
```

**Environment**

Using cordova 8.1.2, and OneSignal-Cordova-SDK 2.4.6

**Comment by sambauwens** [comment]
It might be only for certain categories, because I added other categories now that were successfully created on devices. Although I still have the error whent initializing the app.

**Comment by rgomezp** [comment]
Hello,
Sorry for the delay. Were you able to resolve this?

**Comment by MujtabaFR** [comment]
I found that such error and crash happens (using react-native-onesigna 3.2.14), when creating a category that contains custom notification color which starts with **#** sign such as **#30D2FFFF**
Just change it to **30D2FFFF** and the issue will be resolved

Guess OneSignal should edit the placeholder of this field and remove **#** sign

![Screen Shot 2019-07-15 at 11 14 35 PM](https://user-images.githubusercontent.com/7612635/61246015-87ddd900-a756-11e9-96a5-d5e083012ddc.png)

**Comment by rgomezp** [comment]
@MujtabaFR ,
Thanks for the update. We will make sure to remove the #
