### ISSUE TITLE
ios build failed

### ISSUE THREAD

**Issue by abgit** [OneSignal/OneSignal-Cordova-SDK#534]
**Environment**
Cordova-cli `9.0.0`
Cordova-ios `5.0.1`
xcode `10.2.1`

**Output**
```
Installing "onesignal-cordova-plugin" for ios
"framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
Running command: pod install --verbose
Failed to install 'onesignal-cordova-plugin': Error: pod: Command failed with exit code 31
    at ChildProcess.whenDone (/private/tmp/download/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
Failed to restore plugin "onesignal-cordova-plugin" from config.xml. You might need to try adding it again. Error: Error: pod: Command failed with exit code 31
```
Maybe i'm doing something wrong?

**Comment by jkasten2** [comment]
@abgit "Error: pod: Command failed with exit code 31" normally means the pod could not be found or the specific version of it could not be found.

Please run `pod repo update` and make sure it completes successfully.

**Comment by rgomezp** [comment]
Closing due to no response
