### ISSUE TITLE
No Notifications and Permission dialog on Amazon apps

### ISSUE THREAD

**Issue by sido420** [OneSignal/OneSignal-Cordova-SDK#568]
**Description:**

Hi,

I am having trouble setting up notifications on Amazon devices for my Cordova app although I have followed the setup instructions.

I do get the user id from onesignal but token field is empty. Is that ok? And, obviously the notifications dont show on the device. This is what I get:

```
IDs: {"userId":"67b4xxxa-0xxx-417e-axxx-7yyyxxxxxxxf3","pushToken":""}
```
after running.
```
window.plugins.OneSignal.getIds(function (ids) {
                    console.log('IDs: ' + JSON.stringify(ids));
});
```
I have the api_key.txt file at the right place as per documentation.

Here is the permission status:
```
{"permissionStatus":{"hasPrompted":true,"state":1},"subscriptionStatus":{"userId":"67b4xxxa-0xxx-417e-axxx-7yyyxxxxxxxf3","pushToken":null,"userSubscriptionSetting":true,"subscribed":false},"emailSubscriptionStatus":{"emailUserId":null,"emailAddress":null,"subscribed":false}}
```
for:
```
window.plugins.OneSignal.getPermissionSubscriptionState(function (status) {
console.log(..... status);
})
```
The interesting thing is that I did not see a permission dialog in my Amazon app.

**Environment**
```
cordova -v
7.1.0
```

```
onesignal-cordova-plugin 2.4.3 "OneSignal Push Notifications"
```

**Steps to Reproduce Issue:**
I don't exactly know however can provide you necessary details to troubleshoot. It just does that on my app for some reason and I am not seeing any errors.

**Comment by sido420** [comment]
```
android 6.4.0
```

I have to use this version due to some dependencies and testing is done on it. I am close to launch but stuck with this issue.

**Comment by sido420** [comment]
In the Onesignal portal, I see "No Push Token" for this device. 

Description of error:
"This user has no push token and cannot be targeted"

**Comment by sido420** [comment]
I triggered the following code through console but nothing happens:
```
window.plugins.OneSignal.promptForPushNotificationsWithUserResponse(function(accepted) {
  console.log("User accepted notifications: " + accepted);
});
```

**Comment by sido420** [comment]
any updates on this issue?

**Comment by rgomezp** [comment]
Howdy,
Can you please include the entire log from the devide? Make sure to use the OneSignal `setLogLevel` method

**Comment by sido420** [comment]
Ok will do.

Thanks.

**Comment by sido420** [comment]
Here is what I did:

Cleared adb logs, 
started collecting logs, 
started application, 
moved app to the background, 
tried sending message from other device (to trigger notification on this device).

Here are the logs for `window.plugins.OneSignal.setLogLevel({ logLevel: 6, visualLevel: 0 });`

```
$ adb logcat | egrep -i onesignal
I/art     (30478): Rejecting re-init on previously-failed class java.lang.Class<com.onesignal.JobIntentService$JobServiceEngineImpl>
I/art     (30478): Rejecting re-init on previously-failed class java.lang.Class<com.onesignal.JobIntentService$JobServiceEngineImpl>
W/PluginManager(30478): THREAD WARNING: exec() call to OneSignalPush.setLogLevel blocked the main thread for 22ms. Plugin should use CordovaInterface.getThreadPool().
D/SystemWebChromeClient(30478): file:///android_asset/www/js/compiled-obfs.js?v=1572611271: Line 24 : Cordova Onesignal plugin is starting...
I/OneSignal(30478): restoring notifications
I/OneSignal(30478): Querying DB for notfs to restore: created_time > 1572009373 AND dismissed = 0 AND opened = 0 AND is_summary = 0
D/OneSignal(30478): Starting request to get Android parameters.
D/OneSignal(30478): OneSignalRestClient: Making request to: https://onesignal.com/api/v1/apps/xxxbfc5f-xxxx-xxxx-90a5-25df1513bxxx/android_params.js?player_id=ayyyyyyc-10ce-4yyy-a9c9-45yyyyyyd06d
D/OneSignal(30478): registerUser: registerForPushFired:false, locationFired: true, awlFired: false
W/PluginManager(30478): THREAD WARNING: exec() call to OneSignalPush.init blocked the main thread for 146ms. Plugin should use CordovaInterface.getThreadPool().
V/OneSignal(30478): OneSignalRestClient: After con.getResponseCode  to: https://onesignal.com/api/v1/apps/xxxbfc5f-xxxx-xxxx-90a5-25df1513bxxx/android_params.js?player_id=ayyyyyyc-10ce-4yyy-a9c9-45yyyyyyd06d
D/OneSignal(30478): OneSignalRestClient: Successfully finished request to: https://onesignal.com/api/v1/apps/xxxbfc5f-xxxx-xxxx-90a5-25df1513bxxx/android_params.js?player_id=ayyyyyyc-10ce-4yyy-a9c9-45yyyyyyd06d
D/OneSignal(30478): null RECEIVED JSON: {"awl_list":{},"android_sender_id":"837930529921","chnl_lst":[],"require_email_auth":true,"outcomes":{"direct":{"enabled":false},"indirect":{"notification_attribution":{"minutes_since_displayed":60,"limit":10},"enabled":false},"unattributed":{"enabled":false}},"receive_receipts_enable":true}
I/ReceiverChecker(29542): Found Receiver: com.onesignal.ADMMessageHandler$Receiver with action: com.amazon.device.messaging.intent.REGISTRATION
I/ReceiverChecker(29542): Found Receiver: com.onesignal.ADMMessageHandler$Receiver with action: com.amazon.device.messaging.intent.RECEIVE
E/OneSignal(30478): ADM:onRegistrationError: INVALID_SENDER
E/OneSignal(30478): Please double check that you have a matching package name (NOTE: Case Sensitive), api_key.txt, and the apk was signed with the same Keystore and Alias.
D/OneSignal(30478): registerUser: registerForPushFired:true, locationFired: true, awlFired: true
I/OneSignal(30478): Error getting Google Ad id: 
I/OneSignal(30478): com.google.android.gms.common.GooglePlayServicesNotAvailableException
I/OneSignal(30478): 	at com.google.android.gms.ads.identifier.AdvertisingIdClient.zzc(Unknown Source)
I/OneSignal(30478): 	at com.google.android.gms.ads.identifier.AdvertisingIdClient.start(Unknown Source)
I/OneSignal(30478): 	at com.google.android.gms.ads.identifier.AdvertisingIdClient.getAdvertisingIdInfo(Unknown Source)
I/OneSignal(30478): 	at com.onesignal.AdvertisingIdProviderGPS.getIdentifier(AdvertisingIdProviderGPS.java:45)
I/OneSignal(30478): 	at com.onesignal.OneSignal.registerUserTask(OneSignal.java:1216)
I/OneSignal(30478): 	at com.onesignal.OneSignal.access$2300(OneSignal.java:80)
I/OneSignal(30478): 	at com.onesignal.OneSignal$7.run(OneSignal.java:1199)
I/OneSignal(30478): 	at java.lang.Thread.run(Thread.java:818)
D/OneSignal(30478): curActivity is NOW: null
D/OneSignal(30478): onActivityStopped: com.test.MainActivity
D/OneSignal(30478): curActivity is NOW: null
D/OneSignal(30478): OneSignalRestClient: Making request to: https://onesignal.com/api/v1/players/ayyyyyyc-10ce-4yyy-a9c9-45yyyyyyd06d/on_session
D/OneSignal(30478): OneSignalRestClient: POST SEND JSON: {"app_id":"xxxbfc5f-xxxx-xxxx-90a5-25df1513bxxx"}
V/OneSignal(30478): OneSignalRestClient: After con.getResponseCode  to: https://onesignal.com/api/v1/players/ayyyyyyc-10ce-4yyy-a9c9-45yyyyyyd06d/on_session
D/OneSignal(30478): OneSignalRestClient: Successfully finished request to: https://onesignal.com/api/v1/players/ayyyyyyc-10ce-4yyy-a9c9-45yyyyyyd06d/on_session
D/OneSignal(30478): POST RECEIVED JSON: {"success":true,"id":"ayyyyyyc-10ce-4yyy-a9c9-45yyyyyyd06d"}
I/OneSignal(30478): Device registered, UserId = ayyyyyyc-10ce-4yyy-a9c9-45yyyyyyd06d
V/OneSignal(30478): scheduleLocationUpdateTask:delayMs: 592953
V/OneSignal(30478): scheduleSyncServiceAsJob:atTime: 592953
I/OneSignal(30478): scheduleSyncServiceAsJob:result: 1
I/OneSignal(30478): GetUnsentActiveTime: 16
I/OneSignal(30478): SaveUnsentActiveTime: 23
```

**Comment by sido420** [comment]
Regarding the errors, I already have placed `api_key.txt` at:
```
./platforms/android/api_key.txt
./platforms/android/assets/api_key.txt
```
And, I had followed instructions to generate the file.

**Comment by rgomezp** [comment]
Please make sure you are not using two different Firebase projects with your app (e.g: if you have other SDKs/plugins that require their own project IDs). Can you please confirm you are only using one?

**Comment by rgomezp** [comment]
Closing due to no response

**Comment by sido420** [comment]
I am not using Firebase etc. But, will double check and let you know.
