### ISSUE TITLE
Didn't find class "com.onesignal.NotificationAccentColor.DEFAULT"

### ISSUE THREAD

**Issue by rcpinheiro** [OneSignal/OneSignal-Cordova-SDK#618]
**Description:**
I'm trying to rebuild an old Cordova project on a new computer and the app crashes on a Android phone right after opening.
After some digging I found this error:

`Caused by: java.lang.ClassNotFoundException: Didn't find class "com.onesignal.NotificationAccentColor.DEFAULT" on path: DexPathList[[zip file "/data/app/com.myapp.com-2/base.apk"],nativeLibraryDirectories=[/data/app/com.myapp.com-1/lib/arm, /data/app/com.myapp.com-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /system/vendor/lib]]`

I've tried to uninstall and install OneSignal-Cordova-SDK, change versions and still got this error.
Is this a known problem or there's something wrong on my side?
Thanks in advance!

**Environment**
I'm running 9.0.0 (cordova-lib@9.0.1) and platform android 8.1.0.
Here's the list of my plugins:
`ordova-custom-config 5.1.0 "cordova-custom-config"  
cordova-plugin-app-version 0.1.9 "AppVersion"  
cordova-plugin-browsertab 0.2.0 "cordova-plugin-browsertab"  
cordova-plugin-buildinfo 2.0.2 "BuildInfo"  
cordova-plugin-camera 4.0.1 "Camera"  
cordova-plugin-compat 1.2.0 "Compat"  
cordova-plugin-customurlscheme 4.4.0 "Custom URL scheme"  
cordova-plugin-device 2.0.3 "Device"  
cordova-plugin-file 5.0.0 "File"  
cordova-plugin-file-transfer 1.7.0 "File Transfer"  
cordova-plugin-fingerprint-aio-133fixed 1.3.3 "FingerprintAllInOne"  
cordova-plugin-geolocation 4.0.2-dev "Geolocation"  
cordova-plugin-googlemaps 2.7.0-20191016-0021 "cordova-plugin-googlemaps"  
cordova-plugin-inappbrowser 3.1.0-dev "InAppBrowser"  
cordova-plugin-media 5.0.3 "Media"  
cordova-plugin-whitelist 1.3.3 "Whitelist"  
cordova-plugin-x-socialsharing 5.4.4 "SocialSharing"  
es6-promise-plugin 4.2.2 "Promise"  
onesignal-cordova-plugin 2.8.4 "OneSignal Push Notifications"`  

The full error log:
03-04 23:07:41.441 29363 29363 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate application com.onesignal.NotificationAccentColor.DEFAULT: java.lang.ClassNotFoundException: Didn't find class "com.onesignal.NotificationAccentColor.DEFAULT" on path: DexPathList[[zip file "/data/app/com.myapp.com-2/base.apk"],nativeLibraryDirectories=[/data/app/com.myapp.com-2/lib/arm, /data/app/com.myapp.com-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /system/vendor/lib]]
03-04 23:07:41.441 29363 29363 E AndroidRuntime: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:807)
03-04 23:07:41.441 29363 29363 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5477)
03-04 23:07:41.441 29363 29363 E AndroidRuntime: 	at android.app.ActivityThread.-wrap2(ActivityThread.java)
03-04 23:07:41.441 29363 29363 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595)
03-04 23:07:41.441 29363 29363 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:110)
03-04 23:07:41.441 29363 29363 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:203)
03-04 23:07:41.441 29363 29363 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6251)
03-04 23:07:41.441 29363 29363 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-04 23:07:41.441 29363 29363 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
03-04 23:07:41.441 29363 29363 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
03-04 23:07:41.441 29363 29363 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.onesignal.NotificationAccentColor.DEFAULT" on path: DexPathList[[zip file "/data/app/com.myapp.com-2/base.apk"],nativeLibraryDirectories=[/data/app/com.myapp.com-2/lib/arm, /data/app/com.myapp.com-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /system/vendor/lib]]
03-04 23:07:41.441 29363 29363 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
03-04 23:07:41.441 29363 29363 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
03-04 23:07:41.441 29363 29363 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
03-04 23:07:41.441 29363 29363 E AndroidRuntime: 	at android.app.Instrumentation.newApplication(Instrumentation.java:995)
03-04 23:07:41.441 29363 29363 E AndroidRuntime: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:801)
03-04 23:07:41.441 29363 29363 E AndroidRuntime: 	... 9 more
03-04 23:07:41.448   825  3109 W ActivityManager:   Force finishing activity com.myapp.com/.MainActivity
>

**Comment by rcpinheiro** [comment]
Never mind, the problem was with the heap size of gradle.
