### ISSUE TITLE
 Ionic build android: Please put onesignal-gradle-plugin first OR update to com.android.tools.build:gradle:3.0.0 or newer!

### ISSUE THREAD

**Issue by pookdeveloper** [OneSignal/OneSignal-Cordova-SDK#665]
**Description:**

Error when run:
`cordova platform remove android && cordova platform add android@7.1.0 && ionic cordova build android --release --verbose`

**Environment**

Run command:
`cordova plugin list`

```
com.google.playservices 22.0.0 "Google Play Services for Android"
cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
cordova-plugin-advanced-http 2.5.1 "Advanced HTTP plugin"
cordova-plugin-android-permissions 1.1.0 "Permissions"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-enable-multidex 0.2.0 "Enable Multidex"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-googlemaps 2.7.1 "cordova-plugin-googlemaps"
cordova-plugin-googleplus 8.5.0 "Google SignIn"
cordova-plugin-inappbrowser 4.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-nativegeocoder 3.4.1 "NativeGeocoder"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-request-location-accuracy 2.3.0 "Request Location Accuracy"
cordova-plugin-sign-in-with-apple 0.0.1 "cordova-plugin-sign-in-with-apple"
cordova-plugin-splashscreen 5.0.4 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-sqlite-storage 5.1.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
onesignal-cordova-plugin 2.11.1 "OneSignal Push Notifications"
```

Run command:
`ionic info
`
```
Ionic:

   Ionic CLI                     : 6.11.9 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.4
   @angular-devkit/build-angular : 0.901.10
   @angular-devkit/schematics    : 9.1.10
   @angular/cli                  : 9.1.12
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res (update available: 0.15.1) : 0.3.0
   native-run (update available: 1.2.1)   : 0.3.0

System:

   NodeJS : v12.4.0 (/usr/local/bin/node)
   npm    : 6.14.7
   OS     : macOS Catalina
   Xcode  : Xcode 11.7 Build version 11E801a
```

**Steps to Reproduce Issue:**

Error at compile for android:
cordova platform remove android && cordova platform add android@7.1.0 && ionic cordova build android --release --verbose

**Anything else:**

---->ANDROID_SUPPORT_V4_VERSION = 27.1.1
WARNING: The onesignal-gradle-plugin MUST be before com.android.application!
   Please put onesignal-gradle-plugin first OR update to com.android.tools.build:gradle:3.0.0 or newer!

> Configure project :com.google.playservices:google-play-services_lib
WARNING: Configuration 'debugCompile' is obsolete and has been replaced with 'debugImplementation' and 'debugApi'.
It will be removed in version 5.0 of the Android Gradle plugin.
For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
WARNING: Configuration 'releaseCompile' is obsolete and has been replaced with 'releaseImplementation' and 'releaseApi'.
It will be removed in version 5.0 of the Android Gradle plugin.
For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:lintVitalRelease'.
> This project uses AndroidX dependencies, but the 'android.useAndroidX' property is not enabled. Set this property to true in the gradle.properties file and retry.
  The following AndroidX dependencies are detected: androidx.multidex:multidex:2.0.1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 21s
Command failed with exit code 1: /Users/davidgarcia/Desktop/ionic/Peopleat-Now-App/platforms/android/gradlew cdvBuildRelease -b /Users/davidgarcia/Desktop/ionic/Peopleat-Now-App/platforms/android/build.gradle
Error: Command failed with exit code 1: /Users/davidgarcia/Desktop/ionic/Peopleat-Now-App/platforms/android/gradlew cdvBuildRelease -b /Users/davidgarcia/Desktop/ionic/Peopleat-Now-App/platforms/android/build.gradle
    at makeError (/Users/davidgarcia/Desktop/ionic/Peopleat-Now-App/platforms/android/cordova/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Users/davidgarcia/Desktop/ionic/Peopleat-Now-App/platforms/android/cordova/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)

**Comment by jkasten2** [comment]
Duplicate of #664
