### ISSUE TITLE
NoSuchMethodError: requestPermissions crash on Android

### ISSUE THREAD

**Issue by rbarriuso** [OneSignal/OneSignal-Cordova-SDK#70]
Hi,

We've received the following crash via Fabric's Crashlytics:

```
Fatal Exception: java.lang.NoSuchMethodError: Landroid/app/Activity;.requestPermissions
       at com.onesignal.AndroidSupportV4Compat$ActivityCompatApi23.requestPermissions(AndroidSupportV4Compat.java:78)
       at com.onesignal.AndroidSupportV4Compat$ActivityCompat.requestPermissions(AndroidSupportV4Compat.java:69)
       at com.onesignal.PermissionsActivity.requestPermission(PermissionsActivity.java:60)
       at com.onesignal.PermissionsActivity.onCreate(PermissionsActivity.java:48)
       at android.app.Activity.performCreate(Activity.java:5133)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
       at android.app.ActivityThread.access$600(ActivityThread.java:141)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5103)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

The application is build on Ionic Framework, with the following versions:
* Plugin: onesignal-cordova-plugin@1.13.0
* Platform: android@5.2.1
* Ionic CLI: 1.7.16
* Cordova: 6.3.0

We don't have more information about how to reproduce the issue, but we know that it happened on an Android 4.3.1 device (XT320)
Any clue?

Thanks in advance!.

**Comment by jkasten2** [comment]
@rbarriuso Our Cordova 2.0.4 contains the Android native SDK 3.3.0 which fixes this issue.

https://github.com/OneSignal/OneSignal-Android-SDK/issues/30
