### ISSUE TITLE
Runtime error after inizialization

### ISSUE THREAD

**Issue by alexnoise79** [OneSignal/OneSignal-Cordova-SDK#819]
### What happened?

Application launch correctly but is not possible to get push notificatoins.

In the android runner is possible to see an error immediately after "Initializing Onesignal"

ERROR: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference (see log output for details)

project is in angular published in cordova

### Steps to reproduce?

```Markdown
1. Install Angular version 12
2. add onesignal-ngx v1.0.2 (npm i onesignal-ngx)
3. install cordova 11 (npm i -g cordova)
4. generate new cordova project (cordova create hello com.example.hello HelloWorld)
5. add android 9.1.0 (cordova platform add android@9.1.0)
6. use api 29 and build-tools 29.0.2 for android build
7. init Onesignal inside angular app
8. deploy app
9. copy the content of dist folder inside cordova/www folder
10. run the application using android studio (so you can see the output)
```

### What did you expect to happen?

I expect to receive the notifications, instead i got the runtime error.

Application was previously working as expected

### OneSignal Cordova SDK version

"onesignal-cordova-plugin": "^3.1.1"

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Relevant log output

```Shell
E/PluginManager: Uncaught exception from plugin
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
        at com.onesignal.OneSignalDbHelper.getInstance(OneSignalDbHelper.java:132)
        at com.onesignal.OneSignal.getDBHelperInstance(OneSignal.java:3314)
        at com.onesignal.OneSignal.getInAppMessageController(OneSignal.java:458)
        at com.onesignal.OneSignal.addTriggers(OneSignal.java:3082)
        at com.onesignal.cordova.OneSignalInAppMessagingController.addTriggers(OneSignalInAppMessagingController.java:40)
        at com.onesignal.cordova.OneSignalPush.execute(OneSignalPush.java:392)
        at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
        at org.apache.cordova.PluginManager.exec(PluginManager.java:139)
        at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
        at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:337)
        at android.os.Looper.loopOnce(Looper.java:168)
        at android.os.Looper.loop(Looper.java:299)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alexnoise79** [comment]
Also tested with:

- cordova-android: 11.0.0
- using JAVA 11
- with api 33 and build-tools 33.0.0

application compiles, run and has exactly same error at runtime.
