### ISSUE TITLE
[Bug]: (Android) - Crash everytime I try to open a notification 

### ISSUE THREAD

**Issue by antoineabbou** [OneSignal/OneSignal-Cordova-SDK#820]
### What happened?

The latest version of the SDK (3.2.0) causes each notification opened on Android to crash, it happens when the app is in background or killed. 

I followed each steps described here : [cordova-sdk-setup](https://documentation.onesignal.com/docs/cordova-sdk-setup) 

### Steps to reproduce?

```Markdown
1. Install the onesignal-cordova-plugin (release 3.2.0 - Cordova-Android v9.1.0). 
2. Set this code at the init of the app : 


window.plugins.OneSignal.setAppId(YOUR_APP_ID)
window.plugins.OneSignal.setNotificationOpenedHandler((jsonData) => {
  console.log('jsonData =', jsonData)
})

3. Launch the app on Android 
4. Put the app in background 
5. Send a notification through OneSignal that redirects on a particular path of the app 
6. Click on the notification
```

### What did you expect to happen?

I expected the app to open the app and redirects to the path of the notification without crashing. 

### OneSignal Cordova SDK version

Release 3.2.0

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Relevant log output

```
Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{eco.brief.app/com.onesignal.NotificationOpenedReceiver}: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=apps://app.brief.eco/edition/2022-10-26-358-les-donnees-personnelles-travailleurs-detaches-quels-logements-sont-majoritaires-en-france/ flg=0x10000000 }

_______ 


Caused by android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=apps://app.brief.eco/edition/2022-10-26-358-les-donnees-personnelles-travailleurs-detaches-quels-logements-sont-majoritaires-en-france/ flg=0x10000000 }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2258)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1914)
       at android.app.Activity.startActivityForResult(Activity.java:5326)
       at android.app.Activity.startActivityForResult(Activity.java:5284)
       at android.app.Activity.startActivity(Activity.java:5670)
       at android.app.Activity.startActivity(Activity.java:5623)
       at com.onesignal.OneSignal.openDestinationActivity(OneSignal.java:2443)
       at com.onesignal.OneSignal.handleNotificationOpen(OneSignal.java:2423)
       at com.onesignal.NotificationOpenedProcessor.processIntent(NotificationOpenedProcessor.java:116)
       at com.onesignal.NotificationOpenedProcessor.processFromContext(NotificationOpenedProcessor.java:64)
       at com.onesignal.NotificationOpenedReceiverBase.onCreate(NotificationOpenedReceiverBase.kt:36)
       at android.app.Activity.performCreate(Activity.java:8006)
       at android.app.Activity.performCreate(Activity.java:7990)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3589)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3780)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2251)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:233)
       at android.app.ActivityThread.main(ActivityThread.java:8068)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by antoineabbou** [comment]
Fixed my issue by adding the correct scheme in my config.xml : 

Imagine your launchURL is "apps://my.host.name/the-slug", then the scheme will be : 

```
<universal-links>
    <host name="my.host.name" scheme="apps"/>
  </universal-links>
```

**Comment by swadeshRanjeet** [comment]
> Fixed my issue by adding the correct scheme in my config.xml :
> 
> Imagine your launchURL is "apps://my.host.name/the-slug", then the scheme will be :
> 
> ```
> <universal-links>
>   <host name="my.host.name" scheme="apps"/>
> </universal-links>
> ```

please show me your config file where you change

**Comment by antoineabbou** [comment]
Hi @swadeshRanjeet ! 

You just have to go in your `config.xml` inside `cordova` folder. Inside the `widget` tag, assuming your app name is  `app.host.name`  and the name of your event is `YourEvent`, you can add this :

``` 
<universal-links>
  <host event="YourEvent" name="app.host.name" scheme="apps"/>
</universal-links>
```

**Comment by swadeshRanjeet** [comment]
> Hi @swadeshRanjeet !
> 
> You just have to go in your `config.xml` inside `cordova` folder. Inside the `widget` tag, assuming your app name is `app.host.name` and the name of your event is `YourEvent`, you can add this :
> 
> ```
> <universal-links>
>   <host event="YourEvent" name="app.host.name" scheme="apps"/>
> </universal-links>
> ```
where to find the event="YourEvent" and   name="app.host.name"

**Comment by antoineabbou** [comment]
Hm, what is the name of your app ? 

and `YourEvent` is something you choose, you can call it whatever you want :)

**Comment by swadeshRanjeet** [comment]
> Hm, what is the name of your app ?
> 
> and `YourEvent` is something you choose, you can call it whatever you want :)

**id="com.paragmedical.customer"**

**Comment by swadeshRanjeet** [comment]
> Hm, what is the name of your app ?
> 
> and `YourEvent` is something you choose, you can call it whatever you want :)

my widget id is this == id="com.paragmedical.customer"
