### ISSUE TITLE
[Bug]: Crashes When requesting permission on Android 6.0

### ISSUE THREAD

**Issue by selcuk-sahin** [OneSignal/OneSignal-Cordova-SDK#910]
### What happened?

It seems like the latest version is incompatible with Android 6.0.0, 6.0.1
We have errors on Firebase Crashlytics for 3 users in 1 day

### Steps to reproduce?

```Markdown
1. Install on Model:Nexus 5X
2. Trigger `OneSignal.Notifications.requestPermission();`
3. Crash
```
```Platform
- "@capacitor/android": "^4.8.0"
- "onesignal-cordova-plugin": "^5.0.0",

    minSdkVersion = 22
    compileSdkVersion = 33
    targetSdkVersion = 33

```

### What did you expect to happen?

Users should not crash on this version, or there should be workarounds.

### OneSignal Cordova SDK version

5.0.0

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Relevant log output

```Shell
Fatal Exception: java.lang.NoClassDefFoundError: com.onesignal.cordova.OneSignalController$$ExternalSyntheticLambda0
       at com.onesignal.cordova.OneSignalController.requestPermission(OneSignalController.java:243)
       at com.onesignal.cordova.OneSignalPush.execute(OneSignalPush.java:475)
       at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
       at org.apache.cordova.PluginManager.exec(PluginManager.java:146)
       at com.getcapacitor.MessageHandler.lambda$callCordovaPluginMethod$2$com-getcapacitor-MessageHandler(MessageHandler.java:155)
       at com.getcapacitor.MessageHandler$$ExternalSyntheticLambda2.run(D8$$SyntheticClass)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @selcuk-sahin,

You are able to reproduce this on Android 6 Nexus device, and this is also showing up for some users in crashlytics?

**Comment by selcuk-sahin** [comment]
> Hi @selcuk-sahin,
> 
> You are able to reproduce this on Android 6 Nexus device, and this is also showing up for some users in crashlytics?

Yes, I'm able to reproduce this issue with Andorid 6 Nexus Device.
In crashlytics, I saw various devices with version 5.1 & 6 has the same error.
<img width="514" alt="Screenshot 2023-11-12 at 11 48 04" src="https://github.com/OneSignal/OneSignal-Cordova-SDK/assets/71325531/0c1bb90d-5037-406a-a06e-bd6be70502b4">

However, with the latest SDK version this error is fixed. By installing the latest `onesignal-cordova-plugin 5.0.3`, I can confirm the crash is no more happening to me.
